Change to using UCL instead of ZFS props.
Massive speed improvements along with the beginnings of using shellcheck around the script. Lots of syntax is not consistent around the script anymore.

This may be the last set of changes to iocage as a shell script. There is work underway to port it to a different language.

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -29,20 +29,22 @@ unset LANG
 
 PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 
-if [ "${1}" = "--version" -o "${1}" = "version" ] ; then
-    echo "iocage DEVELOP (2016-02-17)"
+if [ "${1}" = "--version" ] || [ "${1}" = "version" ] ; then
+    echo "iocage DEVELOP (2016-03-23)"
     exit 0
 fi
 
 # Check if the system has ZFS available. That is required for iocage to work properly.
 # Exit if it doesn't.
 if [ "$(zpool list)" = 'no pools available' ] ; then
-    echo "  ERROR: ZFS is required for iocage to work and I can't find any pools available." >&2
+    echo "  ERROR: ZFS is required for iocage to work" \
+        "and I can't find any pools available." >&2
     exit 1
 fi
 
-if [ "$(uname -K)" -lt "903000" ]; then
-    echo "  ERROR: Unsupported RELEASE found. Please upgrade to 9.3-RELEASE or later." >&2
+if [ "$(uname -K)" -lt "903000" ] ; then
+    echo "  ERROR: Unsupported RELEASE found." \
+        " Please upgrade to 9.3-RELEASE or later." >&2
     exit 1
 fi
 
@@ -56,23 +58,40 @@ else
     exit 1
 fi
 
-# Source the libs needed to use the script
+# Source the libs needed to use the script, include shellcheck directives
+# shellcheck source=lib/ioc-cmd
 . "${LIB}/ioc-cmd"
+# shellcheck source=lib/ioc-globals
 . "${LIB}/ioc-globals"
+# shellcheck source=lib/ioc-info
 . "${LIB}/ioc-info"
+# shellcheck source=lib/ioc-help
 . "${LIB}/ioc-help"
+# shellcheck source=lib/ioc-common
 . "${LIB}/ioc-common"
+# shellcheck source=lib/ioc-zfs
 . "${LIB}/ioc-zfs"
+# shellcheck source=lib/ioc-send
 . "${LIB}/ioc-send"
+# shellcheck source=lib/ioc-snapshot
 . "${LIB}/ioc-snapshot"
+# shellcheck source=lib/ioc-upgrade
 . "${LIB}/ioc-upgrade"
+# shellcheck source=lib/ioc-image
 . "${LIB}/ioc-image"
+# shellcheck source=lib/ioc-common
 . "${LIB}/ioc-common"
+# shellcheck source=lib/ioc-rc
 . "${LIB}/ioc-rc"
+# shellcheck source=lib/ioc-network
 . "${LIB}/ioc-network"
+# shellcheck source=lib/ioc-rctl
 . "${LIB}/ioc-rctl"
+# shellcheck source=lib/ioc-configure
 . "${LIB}/ioc-configure"
+# shellcheck source=lib/ioc-hacks
 . "${LIB}/ioc-hacks"
+# shellcheck source=lib/ioc-git
 . "${LIB}/ioc-git"
 
 if [ -z "$1" ] ; then
@@ -85,21 +104,44 @@ if [ "$1" = "-v" ] ; then
     shift
 fi
 
-if [ "$1" = "help" -o "$1" = "--help" -o "$1" = "-h" ] ; then
+if [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] ; then
     __help
     exit 0
 fi
 
-if [ $(__readonly_cmd "$1") != "0" -a "$(whoami)" != "root" ] ; then
+if [ "$(__readonly_cmd "$1")" != "0" ] && [ "$(id -un)" != "root" ] ; then
     echo "* The $1 command needs root credentials!" >&2
+    exit 1
+fi
+
+if [ ! -e "/usr/local/lib/libucl.so" ] || [ ! -e "/usr/local/bin/uclcmd" ] ; then
+    echo "* Please install all dependencies!"
     exit 1
 fi
 
 # Work around zpool activation chicken-egg problem
 # (when activating a pool don't look for an existing one)
 # Also look for an altroot and if it exists change lib/ioc-globals to that value
-if [ "$1" != "activate" -a "$1" != "deactivate" ] ; then
-    __find_mypool
+if [ "$1" != "activate" ] ; then
+    _pool=$(__get_default_prop pool)
+    export pool="${_pool}"
+
+    if [ "${pool}" = "null" ] || [ "${pool}" = "none" ]; then
+        _found="0"
+        for _pool in $(zpool list -H -o name) ; do
+            _mpool=$(zpool get -H comment "${_pool}" | awk '{print $3}')
+
+            if [ "${_mpool}" = "iocage" ] ; then
+                _found="1"
+                __activate "${_pool}"
+                break
+            fi
+        done
+      if [ "${_found}" = "0" ] ; then
+          __die "you need to activate a pool!"
+      fi
+    fi
+
     __check_filesystems
 fi
 
diff --git a/lib/ioc-rctl b/lib/ioc-rctl
--- a/lib/ioc-rctl
+++ b/lib/ioc-rctl
@@ -1,32 +1,28 @@
 #!/bin/sh
 
 __rctl_limits () {
-    local _fulluuid _dataset _value _limit _action _prop _failed \
-          _rlimits
+    local _name _fulluuid _dataset _value _limit _action _prop _failed _rlimits
 
     _failed=0
-    _fulluuid_dataset="$(__get_uuid_and_dataset $1 $2)"
+    _name=$1
+    _dataset="$(__find_jail ${_name})" || exit $?
+    _fulluuid="$(__check_name ${_name} ${_dataset})"
 
-    set ${_fulluuid_dataset}
+    _rlimits="$(__get_jail_prop rlimits ${_fulluuid} ${_dataset})"
 
-    _fulluuid="$1"
-    _dataset="$2"
-
-    _rlimits="$(__get_jail_prop rlimits $_fulluuid $_dataset)"
-
-    if [ $_rlimits == "on" ] ; then
+    if [ ${_rlimits} = "on" ] ; then
         echo -n "  + Applying resource limits"
-        for _prop in $CONF_RCTL ; do
-            _value="$(__get_jail_prop $_prop $_fulluuid $_dataset)"
-            _limit=$(echo $_value | awk 'BEGIN { FS = ":" } ; { print $1 }')
-            _action=$(echo $_value | awk 'BEGIN { FS = ":" } ; { print $2 }')
+        for _prop in ${CONF_RCTL} ; do
+            _value="$(__get_jail_prop ${_prop} ${_fulluuid} ${_dataset})"
+            _limit=$(echo ${_value} | awk 'BEGIN { FS = ":" } ; { print $1 }')
+            _action=$(echo ${_value} | awk 'BEGIN { FS = ":" } ; { print $2 }')
 
-            if [ $_limit == "off" ] ; then
+            if [ ${_limit} = "off" ] ; then
                 continue
             else
-                if [ -z "$_limit" ] || [ -z "$_action" ] ; then
-                    echo -n "  ERROR: incorrect resource limit: $_limit action: "
-                    echo "$_action for property: $_prop"
+                if [ -z "${_limit}" ] || [ -z "${_action}" ] ; then
+                    echo -n "  ERROR: incorrect resource limit: ${_limit} action: "
+                    echo "${_action} for property: ${_prop}"
                     echo "  HINT : check man page for syntax."
                 else
                     rctl -a jail:ioc-${_fulluuid}:${_prop}:${_action}=${_limit}
@@ -37,49 +33,55 @@ __rctl_limits () {
                 fi
             fi
         done
-        if [ $_failed -ne 1 ] ; then
+        if [ ${_failed} -ne 1 ] ; then
             echo " OK"
         fi
     fi
 }
 
 __rctl_list () {
-    local name="$1"
+    local _name _fulluuid _dataset _jid _limits _limit
 
-    if [ -z "$name" ] ; then
+    _name="$1"
+
+    if [ -z "${_name}" ] ; then
         echo "* All active limits:"
         rctl | grep jail
     else
-        local fulluuid="$(__check_name $name)"
-        local jid="$(jls -j ioc-${fulluuid} jid)"
-        local limits="$(rctl -h | grep $fulluuid)"
+        _dataset="$(__find_jail ${_name})" || exit $?
+        _fulluuid="$(__check_name ${_name} ${_dataset})"
+        _jid="$(jls -j ioc-${_fulluuid} jid)"
+        _limits="$(rctl -h | grep ${_fulluuid})"
 
-        echo "* Active limits for jail: $fulluuid"
+        echo "* Active limits for jail: ${_fulluuid}"
 
-        for i in $limits ; do
-            limit=$(echo $i | cut -f 3,4 -d:)
-            echo "  - $limit"
+        for _i in ${_limits} ; do
+            _limit=$(echo ${_i} | cut -f 3,4 -d:)
+            echo "  - ${_limit}"
         done
 
-        if [ ! -z "$jid" ] ; then
-            echo "* CPU set: $(cpuset -g -j $jid | cut -f2 -d:)"
+        if [ ! -z "${_jid}" ] ; then
+            echo "* CPU set: $(cpuset -g -j ${_jid} | cut -f2 -d:)"
         fi
     fi
 }
 
 __rctl_uncap () {
-    local name="$1"
+    local _name _fulluuid _dataset
 
-    if [ -z $name ] ; then
+    _name="$1"
+
+    if [ -z ${_name} ] ; then
         __die "missing UUID!"
     fi
 
-    local fulluuid="$(__check_name $name)"
+    _dataset="$(__find_jail ${_name})" || exit $?
+    _fulluuid="$(__check_name ${_name} ${_dataset})"
 
     echo "  Releasing resource limits.."
-    rctl -r jail:ioc-${fulluuid}
+    rctl -r jail:ioc-${_fulluuid}
     echo "  Listing active rules for jail:"
-    rctl | grep $fulluuid
+    rctl | grep ${_fulluuid}
 }
 
 
@@ -88,18 +90,18 @@ __rctl_inuse () {
 
     _name="$1"
 
-    if [ -z $_name ] ; then
+    if [ -z ${_name} ] ; then
         __rctl_inuse_all
         exit 0
     fi
 
-    _dataset="$(__find_jail $_name)" || exit $?
+    _dataset="$(__find_jail ${_name})" || exit $?
 
-    if [ -z $_dataset ] ; then
-        __die "$_name not found!"
+    if [ -z ${_dataset} ] ; then
+        __die "${_name} not found!"
     fi
 
-    _fulluuid="$(__check_name $_name)"
+    _fulluuid="$(__check_name ${_name} ${_dataset})"
 
     echo "Consumed resources:"
     echo "-------------------"
@@ -114,9 +116,10 @@ __rctl_inuse_all () {
             awk 'BEGIN { FS = "/" } ; { if (length($NF)==36) { print }}')
     _print_head=1
 
-    for _jail in $(echo $_jails) ; do
-        _fulluuid="$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $_jail)"
-        _tag="$(zfs get -H -o value org.freebsd.iocage:tag $_jail)"
+    for _jail in $(echo ${_jails}) ; do
+        # _jail is actually a dataset, so fulluuid needs to be faked.
+        _fulluuid="$(__check_name "name" ${_jail} 2> /dev/null)"
+        _tag="$(__get_jail_prop tag ${_fulluuid} ${_jail})"
         _resources="$(rctl -hu jail:ioc-${_fulluuid})"
         _state="$(__is_running ${_fulluuid})"
 
