enhanced import

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -31,7 +31,7 @@ PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 
 
 if [ "${1}" = "--version" -o "${1}" = "version" ] ; then
-    echo "iocage 1.3.5 (2014/07/03)"
+    echo "iocage 1.3.6 (2014/07/04)"
     exit 0
 fi
 
@@ -70,7 +70,7 @@ mount_fdescfs=1
 enforce_statfs="2"
 children_max="0"
 login_flags='-f root'
-securelevel="3"
+securelevel="2"
 host_hostuuid=$uuid
 allow_set_hostname=1
 allow_sysvipc=0
@@ -1820,21 +1820,45 @@ __import () {
     local name=$1
 
     if [ -z $name ] ; then
-        echo "  ERROR: missing UUID"
+        echo "  ERROR: missing package UUID"
         exit 1
     fi
 
-    if [ -e /iocage/packages/$name.tar.xz ] ; then
-        echo "* Found /iocage/packages/$name.tar.xz"
-        echo "* Importing package $name"
+    local package="`find /iocage/packages/ -name $name\*.tar.xz`"
+    local image="`find /iocage/images/ -name $name\*.tar.xz`"
+    local pcount="`echo $package|wc -w`"
+    local icount="`echo $image|wc -w`"
 
-        if [ ! -e /iocage/packages/$name.sha256 ] ; then
+    if [ $pcount -gt 1 ] ; then
+        echo "  ERROR: multiple matching packages, please narrow down UUID."
+        exit 1
+    elif [ $pcount -eq 1 ] ; then
+        local pcksum="`find /iocage/packages/ -name $name\*.sha256`"
+    fi
+
+    if [ $icount -gt 1 ] ; then
+        echo "  ERROR: multiple matching images, please narrow down UUID."
+        exit 1
+    elif [ $icount -eq 1 ] ; then
+        local icksum="`find /iocage/images/ -name $name\*.sha256`"
+    fi
+
+    if [ $pcount -gt 0 ] && [ $icount -gt 0 ] ; then
+        echo "  ERROR: same UUID is matching both a package and an image."
+        exit 1
+    fi
+
+    if [ $pcount -gt 0 ] ; then
+        echo "* Found package $package"
+        echo "* Importing package $package"
+
+        if [ ! -f $pcksum ] ; then
             echo "  ERROR: missing checksum file!"
             exit 1
         fi
 
-        local new_cksum="`sha256 -q /iocage/packages/$name.tar.xz`"
-        local old_cksum="`cat /iocage/packages/$name.sha256`"
+        local new_cksum="`sha256 -q $package`"
+        local old_cksum="`cat $pcksum`"
         local uuid="`__create_jail create | grep uuid | cut -f2 -d=`"
         local mountpoint="`__get_jail_prop mountpoint $uuid`"
 
@@ -1842,20 +1866,20 @@ __import () {
             echo "  ERROR: checksum mismatch ..exiting"
             exit 1
         else
-            tar -xvJf /iocage/packages/$name.tar.xz -C $mountpoint/root
+            tar -xvJf $package -C $mountpoint/root
         fi
 
-    elif [ -e /iocage/images/$name.tar.xz ] ; then
-        echo "* Found /iocage/images/$name.tar.xz"
-        echo "* Importing image $name"
+    elif [ $icount -gt 0 ] ; then
+        echo "* Found image $image"
+        echo "* Importing image $image"
 
-        if [ ! -e /iocage/images/$name.sha256 ] ; then
+        if [ ! -f $icksum ] ; then
             echo "  ERROR: missing checksum file!"
             exit 1
         fi
 
-        local new_cksum="`sha256 -q /iocage/images/$name.tar.xz`"
-        local old_cksum="`cat /iocage/images/$name.sha256`"
+        local new_cksum="`sha256 -q $image`"
+        local old_cksum="`cat $icksum`"
         local uuid="`__create_jail create -e|tail -1`"
         local mountpoint="`__get_jail_prop mountpoint $uuid`"
 
@@ -1863,7 +1887,7 @@ __import () {
             echo "  ERROR: checksum mismatch ..exiting"
             exit 1
         else
-            tar -xvJf /iocage/images/$name.tar.xz -C $mountpoint/root
+            tar -xvJf $image -C $mountpoint/root
         fi
 
     else
@@ -1871,6 +1895,12 @@ __import () {
         exit 1
     fi
 
+    cat /iocage/jails/${uuid}/root/etc/rc.conf | \
+    sed -E "s/[a-zA-Z0-9]{8,}-.*-.*-.*-[a-zA-Z0-9]{12,}/$uuid/g" \
+    > /iocage/jails/${uuid}/rc.conf
+
+    mv /iocage/jails/${uuid}/rc.conf \
+    /iocage/jails/${uuid}/root/etc/rc.conf
 }
 
 __export () {
@@ -2215,7 +2245,8 @@ SUBCOMMANDS
 
     Import full jail images or differential packages. Images need to be
     present in /iocage/images and packages in /iocage/packages along with
-    along with checksum files.
+    along with checksum files. You can use short UUIDs - do not specify the
+    the full filename only the UUID.
 
   defaults
 
