various fixes

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -229,55 +229,82 @@ __parse_cmd () {
     while [ $# -gt 0 ] ; do
         case "$1" in
             list)       __list_jails $@
+                        exit 0
                 ;;
             console)    __console $2
+                        exit 0
                 ;;
             chroot)     __chroot $2
+                        exit 0
                 ;;
             defaults)   __print_defaults
+                        exit 0
                 ;;
             create)     __export_props $@
                         __create_jail $@
+                        exit 0
                 ;;
             destroy)    __destroy_jail $2
+                        exit 0
                 ;;
             clone)      __export_props $@
                         __clone_jail $2
+                        exit 0
                 ;;
             fetch)      __fetch_release
+                        exit 0
                 ;;
             get)        __get_jail_prop $@
+                        exit 0
                 ;;
             set)        __export_props "$@"
                         __set_jail_prop "$@"
+                        exit 0
                 ;;
             start)      __start_jail $2
+                        exit 0
                 ;;
             stop)       __stop_jail $2
+                        exit 0
                 ;;
             restart)    __restart_jail $2
+                        exit 0
                 ;;
             rcboot)     __rc_jails boot
+                        exit 0
                 ;;
             rcshutdown) __rc_jails shutdown
+                        exit 0
                 ;;
             df)         __print_disk
+                        exit 0
                 ;;
             snapshot)   __snapshot $2
+                        exit 0
                 ;;
             snaplist)   __snaplist $2
+                        exit 0
                 ;;
             snapremove) __snapremove $2 $3
+                        exit 0
                 ;;
             uncap)      __rctl_uncap $2
+                        exit 0
                 ;;
             cap)        __rctl_limits $2
+                        exit 0
                 ;;
             limits)     __rctl_list $2
+                        exit 0
                 ;;
             inuse)      __rctl_used $2
+                        exit 0
                 ;;
             help)       __usage
+                        exit 0
+                ;;
+                *)      __usage
+                        exit 0
                 ;;
         esac
         shift
@@ -512,6 +539,7 @@ __set_jail_prop () {
     local dataset=`__find_jail $name`
     local pname="`echo $property|cut -f 1 -d'='`"
     local pval="`echo $property|cut -f 2 -d'='`"
+    local found="0"
 
     local CONF="$CONF_NET
                 $CONF_JAIL
@@ -521,6 +549,7 @@ __set_jail_prop () {
 
     for prop in $CONF ; do
         if [ "$prop" == "$pname" ] ; then
+            found=1
             zfs set org.freebsd.iocage:${prop}="${pval}" $dataset
         fi
     done
@@ -528,14 +557,21 @@ __set_jail_prop () {
     for prop in $CONF_ZFS ; do
         if [ "$prop" == "$pname" ] ; then
             zfs set $prop="$pval" $dataset
+            found=1
         fi
     done
+
+    if [ $found -ne "1" ] ; then
+        echo "  ERROR: unsupported property: $pname !"
+        exit 1
+    fi
 }
 
 __get_jail_prop () {
     local name=`__get_jail_name "$@"`
     local property=$2
     local dataset=`__find_jail $name`
+    local found="0"
 
     local CONF="$CONF_NET
                 $CONF_JAIL
@@ -545,9 +581,11 @@ __get_jail_prop () {
 
     for prop in $CONF ; do
         if [ $prop == $property ] ; then
+            found=1
             local value=`zfs get -H -o value org.freebsd.iocage:$prop $dataset`
             echo "$value"
         elif [ $property == "all" ] ; then
+            found=1
             local value=`zfs get -H -o value org.freebsd.iocage:$prop \
             $dataset`
             echo "$prop:$value"
@@ -556,10 +594,16 @@ __get_jail_prop () {
 
     for prop in $CONF_ZFS ; do
         if [ $prop == $property ] ; then
+            found=1
             local value=`zfs get -H -o value $prop $dataset`
             echo "$value"
         fi
     done
+
+    if [ $found -ne "1" ] ; then
+        echo "  ERROR: unsupported property: $property !"
+        exit 1
+    fi
 }
 
 __usage () {
@@ -571,6 +615,7 @@ __usage () {
     echo "  iocage list [-t]"
     echo "  iocage start UUID"
     echo "  iocage stop UUID"
+    echo "  iocage restart UUID"
     echo "  iocage rcboot"
     echo "  iocage rcshutdown"
     echo "  iocage console UUID"
@@ -619,6 +664,27 @@ __start_jail () {
     local dataset=`__find_jail $name`
     local template="`__get_jail_prop get template $name`"
     local cpuset="`__get_jail_prop get cpuset $name`"
+    local procfs="`__get_jail_prop get mount_procfs $name`"
+    local state=`jls | grep $name | wc -l`
+    local nics=`__get_jail_prop get interfaces $2 \
+               |awk 'BEGIN { FS = "," } ; { print $1,$2,$3,$4 }'`
+
+    if [ "$state" -eq "1" ] ; then
+        echo "* ${name}: is already up"
+        exit 1
+    fi
+
+    for i in $nics ; do
+        local nic=`echo $i | awk 'BEGIN { FS = ":" } ; { print $1 }'`
+        local bridge=`echo $i | awk 'BEGIN { FS = ":" } ; { print $2 }'`
+
+        if [ -z $nic ] || [ -z $bridge ] ; then
+            echo "  ERROR  : incorrect interfaces property format"
+            echo "  HINT   : check with \"iocage get interfaces $name\""
+            echo "  Example: vnet0:bridge0"
+            exit 1
+        fi
+    done
 
     if [ $template == "yes" ] ; then
         return
@@ -631,13 +697,17 @@ __start_jail () {
         exit 1
     fi
 
+    if [ "$procfs" == "1" ] ; then
+        mount -t procfs proc /iocage/jails/${name}/root/proc
+    fi
+
     echo "* Starting jail $name"
 
     jail -c vnet \
     name="ioc-`__get_jail_prop get host_hostuuid $name`" \
     host.hostname=`__get_jail_prop get hostname $name` \
     path="${jail_path}/root" \
-    securelevel=`__get_jail_prop get seclevel $name` \
+    securelevel=`__get_jail_prop get securelevel $name` \
     host.hostuuid=`__get_jail_prop get host_hostuuid $name` \
     devfs_ruleset=`__get_jail_prop get devfs_ruleset $name` \
     enforce_statfs=`__get_jail_prop get enforce_statfs $name` \
@@ -683,6 +753,7 @@ __start_jail () {
      >> /iocage/log/${name}-console.log 2>&1
 
     zfs set org.freebsd.iocage:last_started=`date "+%F_%T"` $dataset
+
 }
 
 __stop_jail () {
@@ -865,8 +936,8 @@ __networking () {
 
     if [ $action == "start" ] ; then
         for i in $nics ; do
-            local nic=`echo $i | cut -f 1 -d:`
-            local bridge=`echo $i | cut -f 2 -d:`
+            local nic=`echo $i | awk 'BEGIN { FS = ":" } ; { print $1 }'`
+            local bridge=`echo $i | awk 'BEGIN { FS = ":" } ; { print $2 }'`
             epair_a=`ifconfig epair create`
             epair_b=`echo $epair_a | sed s/a\$/b/`
             ifconfig ${epair_a} name ${nic}:${jid}
@@ -914,7 +985,7 @@ __rctl_list () {
     else
         local jid="`jls | grep $name | awk '{ print $1 }'`"
         echo "* Active limits for jail: $name"
-        rctl | grep $name
+        rctl -h | grep $name
         if [ ! -z "$jid" ] ; then
             echo "* CPU affinity: `cpuset -g -j $jid | cut -f2 -d:`"
         fi
@@ -995,9 +1066,14 @@ __promote () {
 }
 
 
-if [ -z "$1" ] ; then
+if [ -z "$1" ] || [ "$1" == "help" ] ; then
     __usage
     exit 0
+fi
+
+if [ "`whoami`" != "root" ] ; then
+    echo "* Only root can manage jails!"
+    exit 1
 fi
 
 __find_mypool
