Reclone basejails at start/stop, add experimental short path support

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -30,7 +30,7 @@ unset LANG
 PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 
 if [ "${1}" = "--version" -o "${1}" = "version" ] ; then
-    echo "iocage 1.4.9 (2015/03/09)"
+    echo "iocage 1.5.0 (2015/03/15)"
     exit 0
 fi
 
@@ -474,6 +474,41 @@ __create_basejail () {
     done
 }
 
+__reclone_basejail () {
+    local name=$1
+
+    if [ -z $name ] ; then
+        echo "  ERROR: missing UUID"
+        exit 1
+    fi
+
+    local dataset=$(__find_jail $name)
+
+    if [ -z $dataset ] ; then
+        echo "  ERROR: $name not found"
+        exit 1
+    fi
+
+    if [ $dataset == "multiple" ] ; then
+        echo "  ERROR: multiple matching UUIDs!"
+        exit 1
+    fi
+
+    local fulluuid="$(__check_name $name)"
+    local jail_release="$(__get_jail_prop release $fulluuid)"
+
+    zfs destroy -rRf $pool/iocage/base/$jail_release@$fulluuid
+    zfs snapshot -r  $pool/iocage/base/$jail_release@$fulluuid
+
+    echo "  This is a basejail, re-cloning jail filesystems.."
+
+    # Re-clone required filesystems 
+    for fs in $bfs_list ; do
+        # echo "  re-cloning: $pool/iocage/jails/$fulluuid/root/$fs"
+        zfs clone $pool/iocage/base/$jail_release/root/$fs@$fulluuid \
+                  $pool/iocage/jails/$fulluuid/root/$fs
+    done
+}
 
 # Fetch release and prepare base ZFS filesystems-----------
 __fetch_release () {
@@ -1016,8 +1051,9 @@ __start_jail () {
         echo "  ERROR: multiple matching UUIDs!"
         exit 1
     fi
-
+    
     local fulluuid="$(__check_name $name)"
+    local jail_type="$(__get_jail_prop type $fulluuid)"
     local tag="$(__get_jail_prop tag $fulluuid)"
     local jail_hostid="$(__get_jail_prop hostid $fulluuid)"
     local jail_path="$(__get_jail_prop mountpoint $fulluuid)"
@@ -1032,6 +1068,11 @@ __start_jail () {
     if [ "$state" -eq "1" ] ; then
         echo "* ${fulluuid}: is already up"
         exit 1
+    fi
+
+    if [ $jail_type == "basejail" ] ; then
+        # Re-clone required filesystems 
+        __reclone_basejail $name
     fi
 
     for i in $nics ; do
@@ -1173,7 +1214,7 @@ __vnet_start () {
     exec.clean="$(__get_jail_prop exec_clean $name)" \
     exec.timeout="$(__get_jail_prop exec_timeout $name)" \
     stop.timeout="$(__get_jail_prop stop_timeout $name)" \
-    mount.fstab="$iocroot/jails/$name/fstab" \
+    mount.fstab="${jail_path}/fstab" \
     mount.devfs="$(__get_jail_prop mount_devfs $name)" \
     mount.fdescfs="$(__get_jail_prop mount_fdescfs $name)" \
     allow.dying \
@@ -1231,7 +1272,7 @@ __legacy_start () {
         exec.clean="$(__get_jail_prop exec_clean $name)" \
         exec.timeout="$(__get_jail_prop exec_timeout $name)" \
         stop.timeout="$(__get_jail_prop stop_timeout $name)" \
-        mount.fstab="$iocroot/jails/$name/fstab" \
+        mount.fstab="${jail_path}/fstab" \
         mount.devfs="$(__get_jail_prop mount_devfs $name)" \
         mount.fdescfs="$(__get_jail_prop mount_fdescfs $name)" \
         allow.dying \
@@ -1269,7 +1310,7 @@ __legacy_start () {
         exec.clean="$(__get_jail_prop exec_clean $name)" \
         exec.timeout="$(__get_jail_prop exec_timeout $name)" \
         stop.timeout="$(__get_jail_prop stop_timeout $name)" \
-        mount.fstab="$iocroot/jails/$name/fstab" \
+        mount.fstab="${jail_path}/fstab" \
         mount.devfs="$(__get_jail_prop mount_devfs $name)" \
         mount.fdescfs="$(__get_jail_prop mount_fdescfs $name)" \
         allow.dying \
@@ -1299,13 +1340,13 @@ __stop_jail () {
     fi
 
     local fulluuid="$(__check_name $name)"
-
+    local jail_path="$(__get_jail_prop mountpoint $name)"
     local tag="$(__get_jail_prop tag $fulluuid)"
     local exec_prestop="$(__findscript $fulluuid prestop)"
     local exec_stop="$(__get_jail_prop exec_stop $fulluuid)"
     local exec_poststop="$(__findscript $fulluuid poststop)"
     local vnet="$(__get_jail_prop vnet $fulluuid)"
-    local state="$(jls | grep $fulluuid | wc -l)"
+    local state="$(jls | grep ${jail_path} | wc -l)"
 
     if [  "$state" -lt "1" ] ; then
         echo "* ${fulluuid}: is already down"
@@ -1361,10 +1402,10 @@ __stop_jail () {
         echo "    FAILED"
     fi
 
-    umount -afvF $iocroot/jails/${fulluuid}/fstab > /dev/null 2>&1
-    umount $iocroot/jails/${fulluuid}/root/dev/fd > /dev/null 2>&1
-    umount $iocroot/jails/${fulluuid}/root/dev    > /dev/null 2>&1
-    umount $iocroot/jails/${fulluuid}/root/proc   > /dev/null 2>&1
+    umount -afvF ${jail_path}/fstab > /dev/null 2>&1
+    umount ${jail_path}/root/dev/fd > /dev/null 2>&1
+    umount ${jail_path}/root/dev    > /dev/null 2>&1
+    umount ${jail_path}/root/proc   > /dev/null 2>&1
 
     if [ -d $iocroot/jails/${fulluuid}/recorded ] ; then
         umount -ft unionfs $iocroot/jails/${fulluuid}/root > /dev/null 2>&1
@@ -1492,7 +1533,8 @@ __list_jails () {
         uuid=$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)
         boot=$(zfs get -H -o value org.freebsd.iocage:boot $jail)
         tag=$(zfs get -H -o value org.freebsd.iocage:tag $jail)
-        state=$(jls | grep $uuid | awk '{print$1}')
+        jail_path=$(zfs get -H -o value mountpoint $jail)
+        state=$(jls | grep ${jail_path} | awk '{print$1}')
         template=$(zfs get -H -o value org.freebsd.iocage:template $jail)
 
         if [ -z "$state" ] ; then
@@ -2107,14 +2149,8 @@ __update () {
     local jail_release="$(__get_jail_prop release $fulluuid)"
 
     if [ $jail_type == "basejail" ] ; then
-        zfs destroy -rRf $pool/iocage/base/$jail_release@$fulluuid
-        zfs snapshot -r  $pool/iocage/base/$jail_release@$fulluuid
-
         # Re-clone required filesystems 
-        for fs in $bfs_list ; do
-            zfs clone $pool/iocage/base/$jail_release/root/$fs@$fulluuid \
-                      $pool/iocage/jails/$fulluuid/root/$fs
-        done
+        __reclone_basejail $name
     else
         echo "* creating back-out snapshot.."
         __snapshot ${fulluuid}@ioc-update_${date}
@@ -2153,10 +2189,16 @@ __upgrade () {
     fi
 
     local fulluuid="$(__check_name $name)"
-
+    local jail_type="$(__get_jail_prop type $fulluuid)"
     local mountpoint="$(__get_jail_prop mountpoint $fulluuid)"
     local date=$(date "+%F_%T")
     local oldrelease="$(zfs get -H -o value org.freebsd.iocage:release $dataset)"
+
+    if [ $jail_type == "basejail" ] ; then
+        # Re-clone required filesystems 
+        __reclone_basejail $name
+        exit 0
+    fi
 
     echo "* creating back-out snapshot.."
     __snapshot ${fulluuid}@ioc-upgrade_${date}
