Check for release version against ABI vs. string to ensure patched kernels work.
Test Plan: Verify on 9.3 test box.

Reviewers: magrview

Reviewed By: magrview

Differential Revision: https://git.pulpie.net/D3

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -447,7 +447,7 @@ __print_release () {
     supported="10.1-RELEASE
                 9.3-RELEASE"
 
-    echo "Supported releases are: " 
+    echo "Supported releases are: "
     for rel in $(echo $supported) ; do
         printf "%15s\n" "$rel"
     done
@@ -508,7 +508,7 @@ __reclone_basejail () {
 
     echo "* $fulluuid is a basejail, re-cloning jail.."
 
-    # Re-clone required filesystems 
+    # Re-clone required filesystems
     for fs in $bfs_list ; do
         # echo "  re-cloning: $pool/iocage/jails/$fulluuid/root/$fs"
         zfs clone $pool/iocage/base/$jail_release/root/$fs@$fulluuid \
@@ -540,7 +540,7 @@ __fetch_release () {
         echo "Invalid release $release specified, exiting.."
         exit 1
     fi
-  
+
     local exist=$(zfs list | grep -w ^$pool/iocage)
     local download_exist=$(zfs list | grep -w ^$pool/iocage/download/$release)
     local rel_exist=$(zfs list | grep -w ^$pool/iocage/releases/$release)
@@ -550,7 +550,7 @@ __fetch_release () {
         zfs set mountpoint=$iocroot $pool/iocage
         zfs create -o compression=lz4 $pool/iocage/jails
         zfs mount -a
-    fi 
+    fi
 
     if [ -z "$download_exist" ] ; then
         zfs create -o compression=lz4 -p $pool/iocage/download/$release
@@ -560,7 +560,7 @@ __fetch_release () {
 
     cd $iocroot/download/$release
     for file in $ftpfiles ; do
-        if [ ! -e "$file" ] ; then        
+        if [ ! -e "$file" ] ; then
             fetch http://$ftphost$ftpdir/$file
         fi
     done
@@ -576,7 +576,7 @@ __fetch_release () {
             tar -C $iocroot/releases/$release/root -xf $file
         fi
     done
-    
+
         echo "* Updating base jail.."
         sleep 2
 
@@ -586,8 +586,8 @@ __fetch_release () {
         env UNAME_r="$release" /usr/sbin/freebsd-update \
             -b $iocroot/releases/$release/root \
             -d $iocroot/releases/$release/root/var/db/freebsd-update/ install
-    
-    if [ ! -d $iocroot/log ] ; then 
+
+    if [ ! -d $iocroot/log ] ; then
         mkdir $iocroot/log
     fi
 
@@ -595,7 +595,7 @@ __fetch_release () {
     chflags -R noschg $iocroot/base/$release/root
     tar --exclude \.zfs --exclude usr/sbin/chown -C $iocroot/releases/$release/root -cf - . | \
     tar --exclude \.zfs --exclude usr/sbin/chown -C $iocroot/base/$release/root -xf -
-    
+
     if [ ! -e "$iocroot/base/$release/root/usr/sbin/chown" ] ; then
        cd $iocroot/base/$release/root/usr/sbin && ln -s ../bin/chgrp chown
     fi
@@ -847,10 +847,10 @@ __set_jail_prop () {
     local pname="$(echo $property|awk 'BEGIN { FS = "=" } ; { print $1 }')"
     local pval="$(echo $property|awk 'BEGIN { FS = "=" } ; { print $2 }')"
 
-    if [ -z "$pname" ] || [ -z "$pval" ] ; then 
+    if [ -z "$pname" ] || [ -z "$pval" ] ; then
         echo "  ERROR: set failed, incorrect property syntax!"
         exit 1
-    fi 
+    fi
 
     local found="0"
 
@@ -1059,7 +1059,7 @@ __start_jail () {
         echo "  ERROR: multiple matching UUIDs!"
         exit 1
     fi
-    
+
     local fulluuid="$(__check_name $name)"
     local jail_type="$(__get_jail_prop type $fulluuid)"
     local tag="$(__get_jail_prop tag $fulluuid)"
@@ -1080,7 +1080,7 @@ __start_jail () {
     fi
 
     if [ $jail_type == "basejail" ] ; then
-        # Re-clone required filesystems 
+        # Re-clone required filesystems
         __reclone_basejail $name
     fi
 
@@ -1172,7 +1172,7 @@ __start_jail () {
         fi
     fi
 
-    echo -n "  + Starting services" 
+    echo -n "  + Starting services"
     jexec ioc-${fulluuid} $(__get_jail_prop exec_start $fulluuid) \
      >> $iocroot/log/${fulluuid}-console.log 2>&1
 
@@ -1194,15 +1194,15 @@ __start_jail () {
 __vnet_start () {
     local name="$1"
     local jail_path="$(__get_jail_prop mountpoint $name)"
-    local fdescfs="fdescfs=\"mount.fdescfs=$(__get_jail_prop mount_fdescfs)\""
-    local tmpfs="allow.mount.tmpfs=\"$(__get_jail_prop allow_mount_tmpfs $name)\""
+    local fdescfs="mount.fdescfs=$(__get_jail_prop mount_fdescfs $name)"
+    local tmpfs="allow.mount.tmpfs=$(__get_jail_prop allow_mount_tmpfs $name)"
 
-    if [ "$(uname -r)" == "9.3-RELEASE" ];
+    if [ "$(uname -U)" == "903000" ];
     then
-	fdescfs=""
-	tmpfs=""
+      fdescfs=""
+      tmpfs=""
     fi
-    
+
     jail -c vnet \
     name="ioc-$(__get_jail_prop host_hostuuid $name)" \
     host.hostname="$(__get_jail_prop hostname $name)" \
@@ -1246,16 +1246,16 @@ __legacy_start () {
     local ip4_addr="$(__get_jail_prop ip4_addr $name)"
     local ip6_addr="$(__get_jail_prop ip6_addr $name)"
 
-    local fdescfs="fdescfs=\"mount.fdescfs=$(__get_jail_prop mount_fdescfs)\""
-    local tmpfs="allow.mount.tmpfs=\"$(__get_jail_prop allow_mount_tmpfs $name)\""
+    local fdescfs="mount.fdescfs=$(__get_jail_prop mount_fdescfs $name)"
+    local tmpfs="allow.mount.tmpfs=$(__get_jail_prop allow_mount_tmpfs $name)"
 
-    if [ "$(uname -r)" == "9.3-RELEASE" ];
+    if [ "$(uname -U)" == "903000" ];
     then
-	fdescfs=""
-	tmpfs=""
+      fdescfs=""
+      tmpfs=""
     fi
-    
-    
+
+
     if [ $ip4_addr == "none" ] ; then
         ip4_addr=""
     fi
@@ -1382,7 +1382,7 @@ __stop_jail () {
 
     echo "* Stopping $fulluuid ($tag)"
 
-    echo -n "  + Running pre-stop" 
+    echo -n "  + Running pre-stop"
     echo "$exec_prestop" | sh
     if [ $? -ne 1 ] ; then
         echo "         OK"
@@ -1502,7 +1502,7 @@ __rc_jails () {
             echo "${priority},${name}" >> $boot_list
         fi
     done
-    
+
     if [ -e $boot_list ] ; then
         local boot_order=$(sort -n $boot_list)
         local shutdown_order=$(sort -rn $boot_list)
@@ -1514,7 +1514,7 @@ __rc_jails () {
     if [ "$action" == "boot" ] ; then
         echo "* [I|O|C] booting jails... "
 
-        for i in $boot_order ; do 
+        for i in $boot_order ; do
             local jail="$(echo $i | cut -f2 -d,)"
             local jail_path="$(__get_jail_prop mountpoint $jail)"
             local state="$(jls | grep ${jail_path} | wc -l)"
@@ -1640,9 +1640,9 @@ __show () {
     for jail in $jails ; do
         local name="$(zfs get -H -o value org.freebsd.iocage:host_hostuuid \
                     $jail)"
-        local value="$(__get_jail_prop $prop $name)" 
+        local value="$(__get_jail_prop $prop $name)"
 
-        printf "%-+.36s  %s\n" "$name"  "$value" 
+        printf "%-+.36s  %s\n" "$name"  "$value"
     done
 }
 
@@ -1746,7 +1746,7 @@ __networking () {
             jexec ioc-${2} route add default $defaultgw > /dev/null
         fi
 
-	if [ "$defaulgw6" != "none" ] ; then
+	if [ "$defaultgw6" != "none" ] ; then
 	    jexec ioc-${2} route add -6 default $defaultgw6 >/dev/null
 	fi
 
@@ -1766,7 +1766,7 @@ __stop_legacy_networking () {
 
     if [ $ip4_addr != "none" ] ; then
         IFS=','
-        for ip in $ip4_addr ; do 
+        for ip in $ip4_addr ; do
             local iface="$(echo $ip | \
                          awk 'BEGIN { FS = "|" } ; { print $1 }')"
             local ip4="$(echo $ip | \
@@ -1821,12 +1821,12 @@ __rctl_limits () {
             value="$(__get_jail_prop $prop $fulluuid)"
             limit=$(echo $value | awk 'BEGIN { FS = ":" } ; { print $1 }')
             action=$(echo $value | awk 'BEGIN { FS = ":" } ; { print $2 }')
-            
+
             if [ $limit == "off" ] ; then
                 continue
             else
                 if [ -z "$limit" ] || [ -z "$action" ] ; then
-                    echo -n "  ERROR: incorrect resource limit: $limit action: " 
+                    echo -n "  ERROR: incorrect resource limit: $limit action: "
                     echo "$action for property: $prop"
                     echo "  HINT : check man page for syntax."
                 else
@@ -2026,10 +2026,10 @@ __snapshot () {
     fi
 
     local date=$(date "+%F_%T")
-   
+
     if [ ! -z $snapshot ] ; then
         zfs snapshot -r ${dataset}@${snapshot}
-    else 
+    else
         zfs snapshot -r ${dataset}@ioc-${date}
     fi
 }
@@ -2072,25 +2072,25 @@ __snaplist () {
         echo "  ERROR: missing UUID"
         exit 1
     fi
-        
+
     local dataset=$(__find_jail $name)
- 
+
     if [ -z $dataset ] ; then
         echo "  ERROR: $name not found"
         exit 1
     fi
-    
+
     if [ $dataset == "multiple" ] ; then
         echo "  ERROR: multiple matching UUIDs!"
         exit 1
     fi
-        
+
     local fulluuid="$(__check_name $name)"
     local snapshots="$(zfs list -Hrt snapshot -d1 $dataset | awk '{print $1}')"
 
     printf "%-36s  %-21s  %s   %s\n" "NAME" "CREATED"\
             "RSIZE" "USED"
-    
+
     for i in $snapshots ; do
         local snapname=$(echo $i|cut -f 2 -d \@)
         local creation="$(zfs get -H -o value creation $i)"
@@ -2207,7 +2207,7 @@ __update () {
     fi
 
     local dataset=$(__find_jail $name)
-    
+
     if [ -z $dataset ] ; then
         echo "  ERROR: $name not found"
         exit 1
@@ -2226,7 +2226,7 @@ __update () {
     local jail_release="$(__get_jail_prop release $fulluuid)"
 
     if [ $jail_type == "basejail" ] ; then
-        # Re-clone required filesystems 
+        # Re-clone required filesystems
         __reclone_basejail $name
     else
         echo "* creating back-out snapshot.."
@@ -2309,21 +2309,21 @@ __upgrade () {
     -b ${mountpoint}/root \
     -d ${mountpoint}/root/var/db/freebsd-update/ \
     -r $release upgrade
-    
-    if [ $? -eq 0 ] ; then 
+
+    if [ $? -eq 0 ] ; then
         while [ $? -eq 0 ] ; do
         env UNAME_r=${oldrelease} /usr/sbin/freebsd-update \
         -b ${mountpoint}/root \
         -d ${mountpoint}/root/var/db/freebsd-update/ \
         -r $release install
     done
-    
+
     # Set jail's zfs property to new release
     zfs set org.freebsd.iocage:release="$release" $dataset
     else
        echo "  Upgrade failed, aborting install."
        exit 1
-    fi 
+    fi
 
     echo " "
     echo "* Once finished don't forget to remove the snapshot!"
@@ -2360,11 +2360,11 @@ __record () {
     local mountpoint="$(__get_jail_prop mountpoint $fulluuid)"
     local union_mount="$(mount -t unionfs | grep $fulluuid | wc -l)"
 
-    if [ ! -d ${mountpoint}/recorded ] ; then 
+    if [ ! -d ${mountpoint}/recorded ] ; then
         mkdir ${mountpoint}/recorded
     fi
 
-   
+
     if [ $action == "start" ] ; then
         echo "* Recording to: ${mountpoint}/recorded"
 
@@ -2385,11 +2385,11 @@ __record () {
         > /dev/null 2>&1
         find ${mountpoint}/recorded/ -name .history -exec rm -f {} \; \
         > /dev/null 2>&1
-    fi 
+    fi
 }
 
 __package () {
-    # create package from recorded changes 
+    # create package from recorded changes
     # sha256 too
     local name=$1
 
@@ -2539,7 +2539,7 @@ __export () {
         echo "  ERROR: multiple matching UUIDs!"
         exit 1
     fi
-        
+
     local fulluuid="$(__check_name $name)"
     local jail_path="$(__get_jail_prop mountpoint $fulluuid)"
     local state=$(jls|grep ${jail_path} | wc -l)
@@ -2718,13 +2718,13 @@ DESCRIPTION
   iocage is a system administration tool for jails designed to simplify
   jail management tasks. It abstracts away the management of ZFS backed jails running VNET
   or shared IP networking with optional support for resource limits.
-  
+
   Both, shared IP based jails and VNET enabled jails are supported.
 
   Each jail has a unique ID (UUID) automatically generated at creation time.
   Using the UUID as a jail identifier means that a jail can be replicated in a
   distributed environment with greater flexibility. This also eliminates
-  potential naming clashes on large scale deployments and helps reduce 
+  potential naming clashes on large scale deployments and helps reduce
   operator error.
 
   Partial UUID calling is supported with every operation, e.g. for
@@ -2811,14 +2811,14 @@ SUBCOMMANDS
 
   list [-t|-r]
 
-    List all jails, if -t is specified list only templates, with -r list downloaded 
+    List all jails, if -t is specified list only templates, with -r list downloaded
     releases.
     Non iocage jail listed, only if jail in UP state.
 
   df
 
     List disk space related information. Available fields:
-    
+
     CRT - compression ratio
     RES - reserved space
     QTA - disk quota
@@ -2836,7 +2836,7 @@ SUBCOMMANDS
   restart UUID|TAG
 
     Soft restart jail. Soft method will restart the jail without destroying
-    the jail's networking and the jail process itself. All processes are gracefully 
+    the jail's networking and the jail process itself. All processes are gracefully
     restarted inside the jail. Useful for quick and graceful restarts.
 
   rcboot
@@ -2869,8 +2869,8 @@ SUBCOMMANDS
   show property
 
     Shows the given property for all jails and templates. Useful to compare
-    settings/properties for all jails. 
-   
+    settings/properties for all jails.
+
     To get the last successfull start time for all jails:
 
         iocage show last_started
@@ -2889,7 +2889,7 @@ SUBCOMMANDS
     Set a property to value.
 
   cap UUID|TAG
-    
+
     Reapply resource limits on jail while it is running.
 
   limits [UUID|TAG]
@@ -2902,7 +2902,7 @@ SUBCOMMANDS
     Release all resource limits, disable limits on the fly.
 
   inuse UUID|TAG
-    
+
     Display consumed resources for a jail.
 
   snapshot UUID|TAG [UUID|TAG@snapshotname]
@@ -3066,7 +3066,7 @@ PROPERTIES
 
     Setting this property to anything other than none will try to configure a
     default route inside a VNET jail.
-  
+
   defaultrouter6=none | ip6address
 
     Setting this property to anything other than none will try to configure a
@@ -3075,12 +3075,12 @@ PROPERTIES
   ip6.addr, ip6.saddrsel, ip6
     A set of IPv6 options for the prison, the counterparts to
     ip4.addr, ip4.saddrsel and ip4 above.
-    
+
   interfaces=vnet0:bridge0,vnet1:bridge1 | vnet0:bridge0
-    
+
     By default there are two interfaces specified with their bridge
     association. Up to four interfaces are supported. Interface configurations
-    are separated by commas. Format is interface:bridge, where left value is 
+    are separated by commas. Format is interface:bridge, where left value is
     the virtual VNET interface name, right value is the bridge name where the
     virtual interface should be attached.
 
@@ -3118,7 +3118,7 @@ PROPERTIES
     files outside of the jail.  See devfs(8) for information on
     how to use devfs rules to limit access to entries in the per-jail
     devfs.  A simple devfs ruleset for jails is available as ruleset
-    #4 in /etc/defaults/devfs.rules    
+    #4 in /etc/defaults/devfs.rules
 
     Default: 4
     Source: jail(8)
@@ -3174,7 +3174,7 @@ PROPERTIES
   exec_poststart="/usr/bin/true"
 
     Command(s) to run in the system environment after a jail is started,
-    and after any exec_start commands have completed. 
+    and after any exec_start commands have completed.
 
     Default: /usr/bin/true
     Source: jail(8)
@@ -3283,7 +3283,7 @@ PROPERTIES
     Source: login(1)
 
   jail_zfs=on | off
-    
+
     Enables automatic ZFS jailing inside the jail. Assigned ZFS dataset will
     be fully controlled by the jail.
     NOTE: Setting this to "on" automatically enables allow_mount=1
@@ -3465,7 +3465,7 @@ PROPERTIES
     This property controls whether the jail is a template. Templates are not
     started by iocage. Set to yes if you intend to convert jail into template.
     (See EXAMPLES section)
-    
+
     Default: no
     Source: local
 
@@ -3670,7 +3670,7 @@ PROPERTIES
     This is for future use, currently not supported.
 
   rlimits=on | off
-    
+
     If set to "on" resource limits will be enforced.
 
     Default: off
@@ -3683,7 +3683,7 @@ PROPERTIES
     Default: off
     Source: cpuset(1)
 RESOURCE LIMITS
-  Resource limits (except cpuset and rlimits) use the following value 
+  Resource limits (except cpuset and rlimits) use the following value
   field formatting in the property: limit:action.
 
   Limit defines how much of the resource a process can use before the
@@ -3863,7 +3863,7 @@ EXAMPLES
     iocage start UUID
 
   Turn on resource limits and apply them:
-  
+
     iocage set rlimits=on UUID
     iocage cap UUID
 
@@ -3892,7 +3892,7 @@ EXAMPLES
     iocage record stop UUID
 
   Create package from recorded session
-  
+
     iocage package UUID
 
   Import package on another host
