Print to stderr when we have an error that doesn't immediately kill the program.
Also update the error message for those running STABLE/CURRENT during creation. This fixes an issue with fetching plugins on them.

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -37,12 +37,12 @@ fi
 # Check if the system has ZFS available. That is required for iocage to work properly.
 # Exit if it doesn't.
 if [ "$(zpool list)" = 'no pools available' ] ; then
-    echo "  ERROR: ZFS is required for iocage to work and I can't find any pools available."
+    echo "  ERROR: ZFS is required for iocage to work and I can't find any pools available." >&2
     exit 1
 fi
 
 if [ "$(uname -K)" -lt "903000" ]; then
-    echo "  ERROR: Unsupported RELEASE found. Please upgrade to 9.3-RELEASE or later."
+    echo "  ERROR: Unsupported RELEASE found. Please upgrade to 9.3-RELEASE or later." >&2
     exit 1
 fi
 
@@ -52,7 +52,7 @@ if [ -e "./lib/ioc-common" ] ; then
 elif [ -e "/usr/local/lib/iocage" ] ; then
     LIB="/usr/local/lib/iocage"
 else
-    echo "ERROR: missing libraries"
+    echo "ERROR: missing libraries" >&2
     exit 1
 fi
 
@@ -86,7 +86,7 @@ if [ "$1" == "help" ] ; then
 fi
 
 if [ $(__readonly_cmd "$1") != "0" -a "$(whoami)" != "root" ] ; then
-    echo "* The $1 command needs root credentials!"
+    echo "* The $1 command needs root credentials!" >&2
     exit 1
 fi
 
diff --git a/lib/ioc-common b/lib/ioc-common
--- a/lib/ioc-common
+++ b/lib/ioc-common
@@ -314,7 +314,7 @@ __fetch_release () {
             done
 
             if [ -z ${match} ] ; then
-                echo "Invalid release ${_release} specified, exiting.."
+                echo "Invalid release ${_release} specified, exiting.." >&2
                 exit 1
             fi
         fi
@@ -346,7 +346,7 @@ __fetch_release () {
         if [ ! -e "${_file}" ] ; then
             fetch http://${ftphost}${ftpdir}/${_file}
             if [ $? -ne 0 ] ; then
-                echo "Failed fetching ${_file}.."
+                echo "Failed fetching ${_file}.." >&2
                 exit 1
             fi
         fi
diff --git a/lib/ioc-git b/lib/ioc-git
--- a/lib/ioc-git
+++ b/lib/ioc-git
@@ -28,10 +28,10 @@ __fetch_plugin () {
         ;;
         *)
             if [ "${_gitlocation}" = "none" -a -z "${iocset_gitlocation}" ] ; then
-                echo ""
-                echo "  ERROR: You must either specify gitlocation= or set a default"
-                echo "  iocage set gitlocation=LOCATION default"
-                echo ""
+                echo "" >&2
+                echo "  ERROR: You must either specify gitlocation= or set a default" >&2
+                echo "  iocage set gitlocation=LOCATION default" >&2
+                echo "" >&2
                 exit 1
             elif [ -n "${iocset_gitlocation}" ] ; then
                 unset _gitlocation
@@ -125,10 +125,10 @@ __fetch_plugin_thick () {
         ;;
         *)
             if [ "${_gitlocation}" = "none" -a -z "${iocset_gitlocation}" ] ; then
-                echo ""
-                echo "  ERROR: You must either specify gitlocation= or set a default"
-                echo "  iocage set gitlocation=LOCATION default"
-                echo ""
+                echo "" >&2
+                echo "  ERROR: You must either specify gitlocation= or set a default" >&2
+                echo "  iocage set gitlocation=LOCATION default" >&2
+                echo "" >&2
                 exit 1
             elif [ -n "${iocset_gitlocation}" ] ; then
                 unset _gitlocation
diff --git a/lib/ioc-image b/lib/ioc-image
--- a/lib/ioc-image
+++ b/lib/ioc-image
@@ -21,7 +21,7 @@ __import_thick () {
         echo "* Importing image ${_image}"
 
         if [ ! -f "${_icksum}" ] ; then
-            echo "  ERROR: Missing checksum file!"
+            echo "  ERROR: Missing checksum file!" >&2
             exit 1
         fi
 
@@ -29,7 +29,7 @@ __import_thick () {
         _old_cksum="$(cat ${_icksum})"
 
         if [ "${_new_cksum}" != "${_old_cksum}" ] ; then
-            echo "  ERROR: Checksum mismatch. Exiting."
+            echo "  ERROR: Checksum mismatch. Exiting." >&2
             exit 1
         else
             # Because any jail being imported this way are thickjails
@@ -198,23 +198,23 @@ __export_thick () {
     _mountpoint="$(__get_jail_prop mountpoint ${_fulluuid})"
 
     if [ -z "${_name}" ] ; then
-        echo "  ERROR: Missing UUID!"
+        echo "  ERROR: Missing UUID!" >&2
         exit 1
     fi
 
     if [ -z "${_dataset}" ] ; then
-        echo "  ERROR: ${_name} not found."
+        echo "  ERROR: ${_name} not found." >&2
         exit 1
     fi
 
     if [ "${_dataset}" = "multiple" ] ; then
-        echo "  ERROR: Multiple matching UUIDs!"
+        echo "  ERROR: Multiple matching UUIDs!" >&2
         exit 1
     fi
 
     if [ "${_state}" -gt "0" ] ; then
-        echo "  ERROR: ${_fulluuid} is running!"
-        echo "  Stop jail before exporting!"
+        echo "  ERROR: ${_fulluuid} is running!" >&2
+        echo "  Stop jail before exporting!" >&2
         exit 1
     fi
 
diff --git a/lib/ioc-info b/lib/ioc-info
--- a/lib/ioc-info
+++ b/lib/ioc-info
@@ -261,15 +261,15 @@ __find_mypool () {
     found="0"
 
     if [ "$_dupcheck" -gt 1 ] ; then
-        echo ""
-        echo "  WARNING: You have more then one pool set for iocage use!"
-        echo ""
-        echo "**** POOLS ****"
-        echo "$_comment"
-        echo "***************"
-        echo ""
-        echo "  Please run 'iocage deactivate' on one of them"
-        echo ""
+        echo "" >&2
+        echo "  WARNING: You have more then one pool set for iocage use!" >&2
+        echo "" >&2
+        echo "**** POOLS ****" >&2
+        echo "$_comment" >&2
+        echo "***************" >&2
+        echo "" >&2
+        echo "  Please run 'iocage deactivate' on one of them" >&2
+        echo "" >&2
         exit 1
     fi
 
@@ -443,7 +443,7 @@ __check_name () {
     local _dataset
 
     if [ -z $name ] ; then
-        echo "ERROR"
+        echo "ERROR" >&2
         exit 1
     fi
 
diff --git a/lib/ioc-rc b/lib/ioc-rc
--- a/lib/ioc-rc
+++ b/lib/ioc-rc
@@ -39,7 +39,7 @@ __start_jail () {
                   ; echo $?)"
 
     if [ "$_state" ] ; then
-        echo "* ${_fulluuid}: is already up"
+        echo "* ${_fulluuid}: is already up" >&2
         exit 1
     fi
 
@@ -59,9 +59,9 @@ __start_jail () {
         _bridge="$(echo $i | awk 'BEGIN { FS = ":" } ; { print $2 }')"
 
         if [ -z $_nic ] || [ -z $_bridge ] ; then
-            echo "  ERROR  : incorrect interfaces property format"
-            echo "  HINT   : check with \"iocage get interfaces $_fulluuid\""
-            echo "  Example: vnet0:bridge0"
+            echo "  ERROR  : incorrect interfaces property format" >&2
+            echo "  HINT   : check with \"iocage get interfaces $_fulluuid\"" >&2
+            echo "  Example: vnet0:bridge0" >&2
             exit 1
         fi
     done
@@ -73,9 +73,9 @@ __start_jail () {
     fi
 
     if [ "$_jail_hostid" != "$hostid" ] ; then
-        echo "ERROR: hostid mismatch, start failed!"
-        echo "    jail hostid: $_jail_hostid"
-        echo "  host's hostid: $hostid"
+        echo "ERROR: hostid mismatch, start failed!" >&2
+        echo "    jail hostid: $_jail_hostid" >&2
+        echo "  host's hostid: $hostid" >&2
         exit 1
     fi
 
@@ -154,7 +154,7 @@ __start_jail () {
             __vnet_start $_fulluuid $_dataset
 
             if [ $? -eq 1 ] ; then
-                echo "  ! Start                FAILED"
+                echo "  ! Start                FAILED" >&2
 
                 if [ "${_jail_type}" = "basejail" -o "${_jail_type}" = "clonejail" ] ; then
                     __umount_basejail ${_fulluuid}
@@ -169,7 +169,7 @@ __start_jail () {
             __networking start $_fulluuid $_dataset
 
             if [ $? -eq 1 ] ; then
-                echo "         FAILED"
+                echo "         FAILED" >&2
 
                 if [ "${_jail_type}" = "basejail" -o "${_jail_type}" = "clonejail" ] ; then
                     __umount_basejail ${_fulluuid}
@@ -180,9 +180,9 @@ __start_jail () {
                 echo "         OK"
             fi
         else
-            echo "  ERROR: start failed for $_fulluuid"
-            echo "  vnet=on but kernel is not VNET capable!"
-            echo "  Turn vnet off for this jail or recompile kernel with VNET."
+            echo "  ERROR: start failed for $_fulluuid" >&2
+            echo "  vnet=on but kernel is not VNET capable!" >&2
+            echo "  Turn vnet off for this jail or recompile kernel with VNET." >&2
 
             if [ "${_jail_type}" = "basejail" -o "${_jail_type}" = "clonejail" ] ; then
                 __umount_basejail ${_fulluuid}
@@ -194,7 +194,7 @@ __start_jail () {
         echo "* Starting $_fulluuid ($_tag)"
         __legacy_start $_fulluuid $_dataset
         if [ $? -eq 1 ] ; then
-            echo "  ! Start                FAILED"
+            echo "  ! Start                FAILED" >&2
             if [ "${_jail_type}" = "basejail" -o "${_jail_type}" = "clonejail" ] ; then
                 __umount_basejail ${_fulluuid}
             fi
@@ -213,7 +213,7 @@ __start_jail () {
         local jid="$(jls -j ioc-${_fulluuid} jid)"
         cpuset -l $_cpuset -j $jid
         if [ $? -eq 1 ] ; then
-            echo "    FAILED"
+            echo "    FAILED" >&2
             if [ "${_jail_type}" = "basejail" -o "${_jail_type}" = "clonejail" ] ; then
                 __umount_basejail ${_fulluuid}
             fi
@@ -234,7 +234,7 @@ __start_jail () {
      >> $iocroot/log/${_fulluuid}-console.log 2>&1
 
     if [ $? -eq 1 ] ; then
-        echo "        FAILED"
+        echo "        FAILED" >&2
         if [ "${_jail_type}" = "basejail" -o "${_jail_type}" = "clonejail" ] ; then
             __umount_basejail ${_fulluuid}
         fi
@@ -480,7 +480,7 @@ __stop_jail () {
     _shortuuid="$(echo ${_fulluuid}|cut -f1 -d\-)"
 
     if [ -z "${_state}" ] ; then
-        echo "* ${_fulluuid}: is already down"
+        echo "* ${_fulluuid}: is already down" >&2
         exit 1
     fi
 
diff --git a/lib/ioc-send b/lib/ioc-send
--- a/lib/ioc-send
+++ b/lib/ioc-send
@@ -15,14 +15,14 @@ __init_host () {
               releases"
 
     if [ -z $_host ] || [ -z $_pool ] ; then
-        echo "ERROR: missing host or pool name"
+        echo "ERROR: missing host or pool name" >&2
         exit 1
     fi
 
     _remote_pool="$(ssh root@$_host zpool get -H -o value name $_pool)"
 
     if [ -z "$_remote_pool" ] ; then
-        echo "ERROR: no remote pool $_pool found"
+        echo "ERROR: no remote pool $_pool found" >&2
         exit 1
     fi
 
diff --git a/lib/ioc-upgrade b/lib/ioc-upgrade
--- a/lib/ioc-upgrade
+++ b/lib/ioc-upgrade
@@ -141,7 +141,7 @@ __upgrade () {
 
     if [ ! -d ${iocroot}/base/${base} ] ; then
         __error "${base} not found!"
-        echo "  Please run iocage fetch first."
+        echo "  Please run iocage fetch first." >&2
         exit 1
     fi
 
@@ -165,8 +165,8 @@ __upgrade () {
             __umount_basejail "${_fulluuid}"
             exit 0
         else
-            echo ""
-            echo "* Upgrade failed! Backing out."
+            echo "" >&2
+            echo "* Upgrade failed! Backing out." >&2
             zfs set org.freebsd.iocage:release="${_oldrelease}" ${_dataset}
             zfs rollback -rRf ${_dataset}/root@ioc-upgrade_$(date +%F)
             zfs destroy ${_dataset}/root@ioc-upgrade_$(date +%F)
@@ -212,7 +212,7 @@ __upgrade () {
                 # Set jail's zfs property to new release
                 zfs set org.freebsd.iocage:release="${base}" ${_dataset}
             else
-                echo "* Upgrade failed, aborting install."
+                echo "* Upgrade failed, aborting install." >&2
                 zfs rollback -rRf ${_dataset}/root@ioc-upgrade_$(date +%F)
                 zfs destroy ${_dataset}/root@ioc-upgrade_$(date +%F)
                 exit 1
diff --git a/lib/ioc-zfs b/lib/ioc-zfs
--- a/lib/ioc-zfs
+++ b/lib/ioc-zfs
@@ -311,20 +311,21 @@ __create_jail () {
                   ; echo $?)"
     _configured="0"
 
-    if [ -z "${_supported_release}" -a "${2}" != "-e" ] ; then
-        echo "  You are not running a production RELEASE."
-        echo "  ERROR: Please specify release=RELEASE."
+    if [ -z "${_supported_release}" -a "${2}" != "-e" -a "${1}" = "create" ] ; then
+        echo "  You are not running a production RELEASE." >&2
+        echo "  ERROR: Please specify base=RELEASE." >&2
         exit 1
     fi
 
     if [ -z "${_installed}" -a -z "${_releases}" -a "${2}" != "-e" ] ; then
         __die "no RELEASEs found locally, run iocage fetch first."
     elif [ -z "${_installed}" -a "${2}" != "-e" ] ; then
-        echo "  RELEASE ${base} not found locally."
-        echo "  Please fetch ${base} or rerun iocage with release=RELEASE"
-        echo ""
-        echo "  These are the releases you have already fetched:"
-        printf "${_releases}\n"
+        echo "  RELEASE ${base} not found locally." >&2
+        echo "  Please fetch ${base}" >&2
+        echo "" >&2
+
+        echo "  These are the RELEASEs you have already fetched:" >&2
+        printf "${_releases}\n" >&2
         exit 1
     fi
 
@@ -718,7 +719,7 @@ __check_filesystems () {
         export iocroot="${_altroot}/iocage"
     elif [ ${_altroot} != "-" -a "$(whoami)" != "root" -a ${iocroot} != "${_altroot}/iocage" ] ; then
         __error "You changed the altroot of ${pool}"
-        echo "  Please run as root to fix."
+        echo "  Please run as root to fix." >&2
         exit 1
     elif [ ${_altroot} == "-" -a "$(whoami)" == "root" ] ; then
         sed -i '' s#.*iocroot.*#iocroot="/iocage"# \
@@ -726,7 +727,7 @@ __check_filesystems () {
         export iocroot="/iocage"
     elif [ ${_altroot} == "-" -a "$(whoami)" != "root" -a ${iocroot} != "/iocage" ] ; then
         __error "You changed the altroot of ${pool}"
-        echo "  Please run as root to fix."
+        echo "  Please run as root to fix." >&2
         exit 1
     fi
 }
