Correct grammar/formatting all around. Using a 'zpool altroot' now works with iocage dynamically. The change results in 'iocroot' essentially being a pointer for the filesystem paths. iocage handles that property now, it will get changed upon every invocation.

diff --git a/lib/ioc-common b/lib/ioc-common
--- a/lib/ioc-common
+++ b/lib/ioc-common
@@ -215,99 +215,99 @@ __fetch_release () {
     local _rel_exist _default_rel _non_interactive
     _default_rel=$(uname -r|cut -f 1,2 -d'-')
 
-    if [ -z "$iocset_release" ] ; then
-  __print_release
+    if [ -z "${iocset_release}" ] ; then
+        __print_release
 
-  echo -n "Please select a release [$release]: "
-  read answer
+        echo -n "Please select a release [${release}]: "
+        read _answer
 
-  if [ -z "$answer" ] ; then
-    answer="$release"
-  else
-    release="$answer"
-    for rel in $(echo $supported) ; do
-      if [ "$answer" == "$rel" ] ; then
-        release="$rel"
-        match="1"
-        break
-      fi
-    done
+        if [ -z "${_answer}" ] ; then
+            _answer="${release}"
+        else
+            release="${_answer}"
+            for _rel in $(echo ${supported}) ; do
+                if [ "${_answer}" == "${_rel}" ] ; then
+                    release="${_rel}"
+                    match="1"
+                    break
+                fi
+            done
 
-    if [ -z $match ] ; then
-      echo "Invalid release $release specified, exiting.."
-      exit 1
-    fi
-  fi
-    fi
-
-
-    _rel_exist=$(zfs list | grep -w ^${pool}${iocroot}/releases/${release})
-
-    if [ -z "$_rel_exist" ] ; then
-        zfs create -o compression=lz4 -p ${pool}${iocroot}/releases/${release}/root
-        zfs create -o compression=lz4 -p ${pool}${iocroot}/download/${release}
+            if [ -z ${match} ] ; then
+                echo "Invalid release ${release} specified, exiting.."
+                exit 1
+            fi
+        fi
     fi
 
-    if [ -z "$ftpdir" ] ; then
-        ftpdir="/pub/FreeBSD/releases/amd64/$release"
+
+    _rel_exist=$(zfs list | grep -w ^${pool}/iocage/releases/${release})
+
+    if [ -z "${_rel_exist}" ] ; then
+        zfs create -o compression=lz4 -p ${pool}/iocage/releases/${release}/root
+        zfs create -o compression=lz4 -p ${pool}/iocage/download/${release}
+    fi
+
+    if [ -z "${ftpdir}" ] ; then
+        ftpdir="/pub/FreeBSD/releases/amd64/${release}"
     fi
 
     cd ${iocroot}/download/${release}
-    for file in $ftpfiles ; do
-        if [ ! -e "$file" ] ; then
-            fetch http://${ftphost}${ftpdir}/${file}
+    for _file in ${ftpfiles} ; do
+        if [ ! -e "${_file}" ] ; then
+            fetch http://${ftphost}${ftpdir}/${_file}
             if [ $? -ne 0 ] ; then
-                echo "Failed fetching $file.."
+                echo "Failed fetching ${_file}.."
                 exit 1
             fi
         fi
     done
 
-    for file in $(echo $ftpfiles) ; do
-        if [ -e "$file" ] ; then
-            echo "Extracting: $file"
+    for _file in $(echo ${ftpfiles}) ; do
+        if [ -e "${_file}" ] ; then
+            echo "Extracting: ${_file}"
             chflags -R noschg ${iocroot}/releases/${release}/root
-            tar -C ${iocroot}/releases/${release}/root -xf $file
+            tar -C ${iocroot}/releases/${release}/root -xf ${_file}
         fi
     done
 
-        echo "* Updating base jail.."
-        sleep 2
+    echo "* Updating base jail.."
+    sleep 2
 
-        _non_interactive="--not-running-from-cron"
-        if [ $(uname -U) -lt 1002000 ] ; then
-            _non_interactive=""
-        fi
-
-        if [ -e $iocroot/releases/$release/root/etc/freebsd-update.conf ] ; then
-            env UNAME_r="$release" env PAGER="/bin/cat" \
-                /usr/sbin/freebsd-update \
-                $_non_interactive \
-                -b $iocroot/releases/$release/root \
-                -f $iocroot/releases/$release/root/etc/freebsd-update.conf \
-                -d $iocroot/releases/$release/root/var/db/freebsd-update/ fetch
-            env UNAME_r="$release" env PAGER="/bin/cat" \
-                /usr/sbin/freebsd-update \
-                -b $iocroot/releases/$release/root \
-                -f $iocroot/releases/$release/root/etc/freebsd-update.conf \
-                -d $iocroot/releases/$release/root/var/db/freebsd-update/ install
-        fi
-
-    if [ ! -d $iocroot/log ] ; then
-        mkdir $iocroot/log
+    _non_interactive="--not-running-from-cron"
+    if [ $(uname -U) -lt 1002000 ] ; then
+        _non_interactive=""
     fi
 
-    __create_basejail $release
-    chflags -R noschg $iocroot/base/$release/root
-    tar --exclude \.zfs --exclude usr/sbin/chown -C $iocroot/releases/$release/root -cf - . | \
-    tar --exclude \.zfs --exclude usr/sbin/chown -C $iocroot/base/$release/root -xf -
-
-    if [ ! -e "$iocroot/base/$release/root/usr/sbin/chown" ] ; then
-       cd $iocroot/base/$release/root/usr/sbin && ln -s ../bin/chgrp chown
+    if [ ! -d ${iocroot}/log ] ; then
+        mkdir ${iocroot}/log
     fi
 
-    etcupdate extract -D $iocroot/base/$release/root \
-    -s $iocroot/base/$release/root/usr/src
+    if [ -e ${iocroot}/releases/${release}/root/etc/freebsd-update.conf ] ; then
+        env UNAME_r="${release}" env PAGER="/bin/cat" \
+            /usr/sbin/freebsd-update \
+            ${_non_interactive} \
+            -b ${iocroot}/releases/${release}/root \
+            -f ${iocroot}/releases/${release}/root/etc/freebsd-update.conf \
+            -d ${iocroot}/releases/${release}/root/var/db/freebsd-update/ fetch
+        env UNAME_r="${release}" env PAGER="/bin/cat" \
+            /usr/sbin/freebsd-update \
+            -b ${iocroot}/releases/${release}/root \
+            -f ${iocroot}/releases/${release}/root/etc/freebsd-update.conf \
+            -d ${iocroot}/releases/${release}/root/var/db/freebsd-update/ install
+    fi
+
+    __create_basejail ${release}
+    chflags -R noschg ${iocroot}/base/${release}/root
+    tar --exclude \.zfs --exclude usr/sbin/chown -C ${iocroot}/releases/${release}/root -cf - . | \
+    tar --exclude \.zfs --exclude usr/sbin/chown -C ${iocroot}/base/${release}/root -xf -
+
+    if [ ! -e "${iocroot}/base/${release}/root/usr/sbin/chown" ] ; then
+       cd ${iocroot}/base/${release}/root/usr/sbin && ln -s ../bin/chgrp chown
+    fi
+
+    etcupdate extract -D ${iocroot}/base/${release}/root \
+    -s ${iocroot}/base/${release}/root/usr/src
 }
 
 # reads tag property from given jail dataset
diff --git a/lib/ioc-zfs b/lib/ioc-zfs
--- a/lib/ioc-zfs
+++ b/lib/ioc-zfs
@@ -44,6 +44,7 @@ __clean () {
             if [ "$_answer" == "Y" -o "$_answer" == "y" ] ; then
                 echo "  Destroying $pool/iocage"
                 zfs destroy -rRf $pool/iocage
+                rm -rf ${iocroot}
                 exit 0
             else
                 echo "  Command not confirmed.  No action taken."
@@ -85,7 +86,7 @@ __clean () {
                 echo "  Destroying $pool/iocage/jails"
                 zfs destroy -rRf $pool/iocage/jails
                 echo "  Cleaning TAGs at $pool/iocage/tags"
-                rm -f ${iocroot}/tags/*
+                rm -rf ${_iocroot}/tags
                 exit 0
             else
                 echo "  Command not confirmed.  No action taken."
@@ -101,10 +102,16 @@ __create_basejail () {
     _release="$1"
 
     echo ""
-    echo "Creating basejail ZFS datasets... please wait."
+    echo "* Creating basejail ZFS datasets... please wait."
+    zfs create -o compression=lz4 -p ${pool}/iocage/base/${_release}/root
+    zfs set mountpoint=/iocage/base/${_release}/root \
+        ${pool}/iocage/base/${_release}/root
 
-    for fs in $(echo $bfs_list) ; do
-        zfs create -o compression=lz4 -p $pool/iocage/base/${_release}/root/$fs
+    for _fs in $(echo ${bfs_list}) ; do
+        zfs create -o compression=lz4 -p \
+            ${pool}/iocage/base/${_release}/root/${_fs}
+        zfs set mountpoint=/iocage/base/${_release}/root/${_fs} \
+            ${pool}/iocage/base/${_release}/root/${_fs}
     done
 }
 
@@ -132,97 +139,97 @@ __create_jail () {
     local _installed _releases _zfsconfig _supported_release _configured \
           _zfsconfig
 
-    _installed=$(zfs list -r $pool/iocage/releases|grep $release)
+    _installed=$(zfs list -r ${pool}/iocage/releases|grep ${release})
     _releases=$(__list_jails -r|grep -v "Downloaded releases:")
-    _supported_release=$(echo "$release" | grep "RELEASE")
+    _supported_release=$(echo "${release}" | grep "RELEASE")
     _zfsconfig="$(__configure_jail generate)"
 
     _configured="0"
 
-    if [ -z "$_supported_release" ] ; then
+    if [ -z "${_supported_release}" ] ; then
         echo "  You are not running a production RELEASE."
         echo "  ERROR: Please specify release=RELEASE."
         exit 1
     fi
 
-    if [ -z "$_installed" -a -z "$_releases" ] ; then
+    if [ -z "${_installed}" -a -z "${_releases}" ] ; then
         echo "  ERROR: No RELEASEs found locally, run iocage fetch first."
         exit 1
-    elif [ -z "$_installed" ] ; then
-        echo "  RELEASE $release not found locally."
-        echo "  Please fetch $release or rerun iocage with release=RELEASE"
+    elif [ -z "${_installed}" ] ; then
+        echo "  RELEASE ${release} not found locally."
+        echo "  Please fetch ${release} or rerun iocage with release=RELEASE"
         echo ""
         echo "  These are the releases you have already fetched:"
-        echo "  $_releases"
+        echo "  ${_releases}"
         exit 1
     fi
 
     if [ "${2}" = "-c" ] ; then
-        fs_list=$(zfs list -rH -o name $pool/iocage/releases/$release)
-        zfs snapshot -r $pool/iocage/releases/$release@$uuid
-        for fs in $fs_list ; do
-            cfs=$(echo $fs | sed s#/releases/$release#/jails/$uuid#g)
-            eval "zfs clone ${_zfsconfig} \"$fs@$uuid\" \"$cfs\""
+        fs_list=$(zfs list -rH -o name ${pool}/iocage/releases/${release})
+        zfs snapshot -r ${pool}/iocage/releases/${release}@${uuid}
+        for fs in ${fs_list} ; do
+            cfs=$(echo ${fs} | sed s#/releases/${release}#/jails/${uuid}#g)
+            eval "zfs clone ${_zfsconfig} \"${fs}@${uuid}\" \"${cfs}\""
         done
         _configured="1"
     elif [ "${2}" = "-e" ] ; then
-        eval "zfs create -p ${_zfsconfig} \"$pool/iocage/jails/$uuid\""
-        zfs create -p $pool/iocage/jails/$uuid/root
+        eval "zfs create -p ${_zfsconfig} \"${pool}/iocage/jails/${uuid}\""
+        zfs create -p ${pool}/iocage/jails/${uuid}/root
         _configured="1"
     elif [ "${2}" = "-b" ] ; then
         export type=basejail
-        zfs snapshot -r $pool/iocage/base@$uuid
-        eval "zfs create -p ${_zfsconfig} \"$pool/iocage/jails/$uuid\""
-        __set_jail_prop type=basejail ${uuid} $pool/iocage/jails/$uuid
-        zfs create -o compression=lz4 -p $pool/iocage/jails/$uuid/root/usr
+        zfs snapshot -r ${pool}/iocage/base@${uuid}
+        eval "zfs create -p ${_zfsconfig} \"${pool}/iocage/jails/${uuid}\""
+        __set_jail_prop type=basejail ${uuid} ${pool}/iocage/jails/${uuid}
+        zfs create -o compression=lz4 -p ${pool}/iocage/jails/${uuid}/root/usr
 
-        for fs in $bfs_list ; do
+        for _fs in ${bfs_list} ; do
             zfs clone -o compression=lz4 -o readonly=on \
-            $pool/iocage/base/${release}/root/$fs@$uuid \
-            $pool/iocage/jails/$uuid/root/$fs
+            ${pool}/iocage/base/${release}/root/${_fs}@${uuid} \
+            ${pool}/iocage/jails/${uuid}/root/${_fs}
         done
 
-        for dir in $bdir_list ; do
-            cp -a $iocroot/base/${release}/root/$dir \
-                  $iocroot/jails/$uuid/root/$dir
+        for _dir in ${bdir_list} ; do
+            cp -a ${iocroot}/base/${release}/root/${_dir} \
+                  ${iocroot}/jails/${uuid}/root/${_dir}
         done
         _configured="1"
     else
-        eval "zfs create -p ${_zfsconfig} \"$pool/iocage/jails/$uuid\""
+        eval "zfs create -p ${_zfsconfig} \"${pool}/iocage/jails/${uuid}\""
         _configured="1"
-        zfs snapshot -r $pool/iocage/releases/$release@$uuid
-        zfs send     -R $pool/iocage/releases/$release/root@$uuid | \
-        zfs recv        $pool/iocage/jails/$uuid/root
-        zfs destroy  -r $pool/iocage/releases/$release@$uuid
-        zfs destroy  -r $pool/iocage/jails/$uuid/root@$uuid
+        zfs snapshot -r ${pool}/iocage/releases/${release}@${uuid}
+        zfs send     -R ${pool}/iocage/releases/${release}/root@${uuid} | \
+        zfs recv        ${pool}/iocage/jails/${uuid}/root
+        zfs destroy  -r ${pool}/iocage/releases/${release}@${uuid}
+        zfs destroy  -r ${pool}/iocage/jails/${uuid}/root@${uuid}
     fi
 
-    touch $iocroot/jails/$uuid/fstab
+    touch ${iocroot}/jails/${uuid}/fstab
 
     # remove any residual clone snapshots carried over from the RELEASE datasets
-    __snapremove ${uuid}@ALL $pool/iocage/jails/$uuid
+    __snapremove ${uuid}@ALL ${pool}/iocage/jails/${uuid}
 
     # at create time set the default rc.conf
     if [ "${2}" != "-e" ] ; then
-        echo "hostname=\"${hostname}\"" > $iocroot/jails/${uuid}/root/etc/rc.conf
+        echo "hostname=\"${hostname}\"" > ${iocroot}/jails/${uuid}/root/etc/rc.conf
         __jail_rc_conf >> \
-        $iocroot/jails/${uuid}/root/etc/rc.conf
-        __resolv_conf ${uuid} > $iocroot/jails/${uuid}/root/etc/resolv.conf
+        ${iocroot}/jails/${uuid}/root/etc/rc.conf
+        __resolv_conf ${uuid} > ${iocroot}/jails/${uuid}/root/etc/resolv.conf
     elif [ "${2}" = "-e" ] ; then
-        echo $uuid
+        echo ${uuid}
     fi
 
-    zfs create -o compression=lz4 ${pool}/$jail_zfs_dataset
-    zfs set mountpoint=none ${pool}/$jail_zfs_dataset
-    zfs set jailed=on ${pool}/$jail_zfs_dataset
+    zfs create -o compression=lz4 ${pool}/${jail_zfs_dataset}
+    zfs set mountpoint=none ${pool}/${jail_zfs_dataset}
+    zfs set jailed=on ${pool}/${jail_zfs_dataset}
 
     # configure the jail mountpoint
-    __hack88_mount ${uuid} $pool/iocage/jails/$uuid
+        __hack88_mount ${uuid} ${pool}/iocage/jails/${uuid}
 
     # Install extra packages
     # this requires working resolv.conf in jail
-    if [ "$pkglist" != "none" ] ; then
-        __pkg_install "$iocroot/jails/${uuid}/root"
+    if [ "${pkglist}" != "none" ] ; then
+        __pkg_install "${iocroot}/jails/${uuid}/root"
     fi
 }
 
@@ -365,32 +372,43 @@ __destroy_func () {
 # check if our datasets exist, if not create them
 # fixes https://github.com/iocage/iocage/issues/80
 __check_filesystems () {
+    local _altroot _filesystems _missing
 
-    local _filesystems _missing
     _missing=0
-
-    _filesystems="${iocroot}
-                  ${iocroot}/jails
-                  ${iocroot}/.defaults
-                  ${iocroot}/download
-                  ${iocroot}/releases"
+    _altroot="$(zpool get -H altroot ${pool} | awk '{print $3}')"
+    # Prepend iocage/ so we can properly set a mount on the root 'iocage'
+    # dataset.
+    _filesystems="iocage
+                  iocage/.defaults
+                  iocage/download
+                  iocage/jails
+                  iocage/releases"
 
     # Loop through and make sure the filesystems exist. Make sure you are root
     for _fs in $(echo ${_filesystems}) ; do
-        zfs get -H creation ${pool}${_fs} > /dev/null 2>&1
+        zfs get -H creation ${pool}/${_fs} > /dev/null 2>&1
         if [ $? -ne 0 ] ; then
             _missing=1
             if [ "$(whoami)" != "root" ] ; then
                 echo "  ERROR: Please run as root to create missing datasets."
                 exit 1
             else
-                echo "  INFO: Creating ${pool}${_fs}"
-                zfs create -p ${pool}${_fs}
-                zfs set mountpoint=${_fs} ${pool}${_fs}
-            if [ ${_fs} == "${iocroot}/.defaults" ] ; then
-                __reset_jail_props default > /dev/null 2>&1
+                echo "  INFO: Creating ${pool}/${_fs}"
+                zfs create -p ${pool}/${_fs}
+                zfs set mountpoint=/${_fs} ${pool}/${_fs}
+                if [ ${_fs} == "iocage/.defaults" ] ; then
+                    __reset_jail_props default  > /dev/null 2>&1
+                    if [ $_altroot != "-" ] ; then
+                        sed -i '' s#.*iocroot.*#iocroot="${_altroot}/iocage"# \
+                            "${LIB}/ioc-globals"
+                        export iocroot="${_altroot}/iocage"
+                    elif [ $_altroot == "-" ] ; then
+                        sed -i '' s#.*iocroot.*#iocroot="/iocage"# \
+                            "${LIB}/ioc-globals"
+                        export iocroot="/iocage"
+                    fi
+                fi
             fi
-          fi
         fi
     done
 
@@ -398,7 +416,28 @@ __check_filesystems () {
         zfs mount -a
     fi
 
-    export jail_datasets="$(zfs list -d1 -rH -o name $pool/iocage/jails \
+    export jail_datasets="$(zfs list -d1 -rH -o name ${pool}/iocage/jails \
                           | grep -E \
-                          "^$pool/iocage/jails/[a-zA-Z0-9]{8,}-.*-.*-.*-[a-zA-Z0-9]{12,}$")"
+                          "^${pool}/iocage/jails/[a-zA-Z0-9]{8,}-.*-.*-.*-[a-zA-Z0-9]{12,}$")"
+
+    # Checks to see if the user changed the altroot and modify ioc-globals
+    # If the user decided to unset their altroot, they need to run again as
+    # root to set it back to the default location
+    if [ ${_altroot} != "-" -a "$(whoami)" == "root" ] ; then
+        sed -i '' s#.*iocroot.*#iocroot="${_altroot}/iocage"# \
+            "${LIB}/ioc-globals"
+        export iocroot="${_altroot}/iocage"
+    elif [ ${_altroot} != "-" -a "$(whoami)" != "root" -a ${iocroot} != "${_altroot}/iocage" ] ; then
+        echo "  ERROR: You changed the altroot of ${pool}"
+        echo "  Please run as root to fix."
+        exit 1
+    elif [ ${_altroot} == "-" -a "$(whoami)" == "root" ] ; then
+        sed -i '' s#.*iocroot.*#iocroot="/iocage"# \
+            "${LIB}/ioc-globals"
+        export iocroot="/iocage"
+    elif [ ${_altroot} == "-" -a "$(whoami)" != "root" -a ${iocroot} != "/iocage" ] ; then
+        echo "  ERROR: You changed the altroot of ${pool}"
+        echo "  Please run as root to fix."
+        exit 1
+    fi
 }
