introduce __die function to log to stderr and die, fixes #178

diff --git a/lib/ioc-common b/lib/ioc-common
--- a/lib/ioc-common
+++ b/lib/ioc-common
@@ -350,3 +350,9 @@ __unlink_tag () {
         find $iocroot/tags -type l -lname "${_mountpoint}*" -exec rm -f \{\} \;
     fi
 }
+
+# Log error to stderr and die
+__die () {
+    echo "  ERROR: $@" >&2
+    exit 1
+}
