Added dry run switch for updating 'iocage update -n UUID|TAG'. Only works for git jails currently. Fixed miscellaneous whitespace issues and grammar.

diff --git a/lib/ioc-git b/lib/ioc-git
--- a/lib/ioc-git
+++ b/lib/ioc-git
@@ -1,6 +1,8 @@
 #!/bin/sh
+
 __pull () {
     local _gitlocation _jail_type _jail_path
+
     _gitlocation="$(zfs get -H -o value org.freebsd.iocage:gitlocation \
                   ${pool}${iocroot}/.defaults)"
 
@@ -17,20 +19,20 @@ __pull () {
     # Check to see if the url begins with these otherwise use gitlocation
     case "$1" in
         http://*|https://*|git://*)
-          unset _gitlocation
-          _gitlocation="$1"
+            unset _gitlocation
+            _gitlocation="$1"
         ;;
         *)
-        if [ "$_gitlocation" = "none" -a -z "$iocset_gitlocation" ] ; then
-            echo ""
-            echo "  ERROR: You must either specify gitlocation= or set a default"
-            echo "  iocage set gitlocation=LOCATION default"
-            echo ""
-            exit 1
-        elif [ -n "$iocset_gitlocation" ] ; then
-            unset _gitlocation
-            _gitlocation="$iocset_gitlocation"
-        fi
+            if [ "$_gitlocation" = "none" -a -z "$iocset_gitlocation" ] ; then
+                echo ""
+                echo "  ERROR: You must either specify gitlocation= or set a default"
+                echo "  iocage set gitlocation=LOCATION default"
+                echo ""
+                exit 1
+            elif [ -n "$iocset_gitlocation" ] ; then
+                unset _gitlocation
+                _gitlocation="$iocset_gitlocation"
+            fi
         ;;
     esac
 
@@ -106,7 +108,7 @@ __push () {
           git commit
           git push -u "$2"
     if [ -z $_match ] ; then
-        echo "Invalid repo $_gitrepo specified. Exiting."
+        echo "  ERROR: Invalid repo $_gitrepo specified. Exiting."
         exit 1
     fi
   fi
diff --git a/lib/ioc-upgrade b/lib/ioc-upgrade
--- a/lib/ioc-upgrade
+++ b/lib/ioc-upgrade
@@ -1,70 +1,102 @@
 #!/bin/sh
 
 __update () {
-    local name=$1
+  local _name _dataset _fulluuid _mountpoint _date _jail_type
 
-    if [ -z $name ] ; then
-        echo "  ERROR: missing UUID"
-        exit 1
-    fi
+  _name=$2
 
-    local dataset=$(__find_jail $name)
+    case "$1" in
+        -n)
+            _dataset=$(__find_jail $_name)
+            _fulluuid="$(__check_name $_name)"
+            _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
+            _jail_type="$(__get_jail_prop type $_fulluuid)"
 
-    if [ -z $dataset ] ; then
-        echo "  ERROR: $name not found"
-        exit 1
-    fi
+            case $_jail_type in
+                gitjail)
+                    git -C $_mountpoint/root remote update
+                    git -C $_mountpoint/root status -uno
+                ;;
+            esac
+        ;;
+        *)
+            shift 3
+            _name=$1
+            _dataset=$(__find_jail $_name)
+            _fulluuid="$(__check_name $_name)"
+            _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
+            _date=$(date "+%F_%T")
+            _jail_type="$(__get_jail_prop type $_fulluuid)"
 
-    if [ $dataset == "multiple" ] ; then
-        echo "  ERROR: multiple matching UUIDs!"
-        exit 1
-    fi
+            case $_jail_type in
+                basejail)
+                    # Re-clone required filesystems
+                    __reclone_basejail $_name
+                ;;
+                gitjail)
+                    git -C $_mountpoint/root pull
+                ;;
+                jail)
+                    echo "* Creating back-out snapshot."
+                    __snapshot ${_fulluuid}@ioc-update_${_date}
 
-    local fulluuid="$(__check_name $name)"
+                    echo "* Updating jail.."
+                    env UNAME_r="$release" env PAGER="/bin/cat" \
+                        /usr/sbin/freebsd-update \
+                        -b ${_mountpoint}/root \
+                        -d ${_mountpoint}/root/var/db/freebsd-update/ fetch
+                    env UNAME_r="$release" env PAGER="/bin/cat" \
+                        /usr/sbin/freebsd-update \
+                        -b ${_mountpoint}/root \
+                        -d ${_mountpoint}/root/var/db/freebsd-update/ install
 
-    local mountpoint="$(__get_jail_prop mountpoint $fulluuid)"
-    local date=$(date "+%F_%T")
-    local jail_type="$(__get_jail_prop type $fulluuid)"
-    local jail_release="$(__get_jail_prop release $fulluuid)"
+                    echo ""
+                    echo "* Once finished don't forget to remove the snapshot!"
+                ;;
+            esac
 
-    if [ $jail_type == "basejail" ] ; then
-        # Re-clone required filesystems
-        __reclone_basejail $name
-    else
-        echo "* creating back-out snapshot.."
-        __snapshot ${fulluuid}@ioc-update_${date}
+            if [ -z $_name ] ; then
+                echo "  ERROR: Missing UUID!"
+                exit 1
+            fi
 
-        echo "* Updating jail.."
-        env UNAME_r="$release" env PAGER="/bin/cat" \
-            /usr/sbin/freebsd-update \
-            -b ${mountpoint}/root \
-            -d ${mountpoint}/root/var/db/freebsd-update/ fetch
-        env UNAME_r="$release" env PAGER="/bin/cat" \
-            /usr/sbin/freebsd-update \
-            -b ${mountpoint}/root \
-            -d ${mountpoint}/root/var/db/freebsd-update/ install
+            if [ -z $_dataset ] ; then
+                echo "  ERROR: $_name not found."
+                exit 1
+            fi
 
-        echo " "
-        echo "* Once finished don't forget to remove the snapshot!"
-    fi
+            if [ $_dataset == "multiple" ] ; then
+                echo "  ERROR: Multiple matching UUIDs!"
+                exit 1
+            fi
+        ;;
+      esac
 }
 
 __upgrade () {
-    local name=$1
-    if [ -z $name ] ; then
-        echo "  ERROR: missing UUID"
+    local _name _dataset _fulluuid _jail_type _jail_release _mountpoint _date \
+          _oldrelease
+
+    _name=$1
+    _dataset=$(__find_jail $_name)
+    _fulluuid="$(__check_name $_name)"
+    _jail_type="$(__get_jail_prop type $_fulluuid)"
+    _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
+    _date=$(date "+%F_%T")
+    _oldrelease="$(zfs get -H -o value org.freebsd.iocage:release $_dataset)"
+
+    if [ -z $_name ] ; then
+        echo "  ERROR: Missing UUID!"
         exit 1
     fi
 
-    local dataset=$(__find_jail $name)
-
-    if [ -z $dataset ] ; then
-        echo "  ERROR: $name not found"
+    if [ -z $_dataset ] ; then
+        echo "  ERROR: $_name not found."
         exit 1
     fi
 
-    if [ $dataset == "multiple" ] ; then
-        echo "  ERROR: multiple matching UUIDs!"
+    if [ $_dataset == "multiple" ] ; then
+        echo "  ERROR: Multiple matching UUIDs!"
         exit 1
     fi
 
@@ -74,62 +106,56 @@ __upgrade () {
         exit 1
     fi
 
-    local fulluuid="$(__check_name $name)"
-    local jail_type="$(__get_jail_prop type $fulluuid)"
-    local jail_release="$(__get_jail_prop release $fulluuid)"
-    local mountpoint="$(__get_jail_prop mountpoint $fulluuid)"
-    local date=$(date "+%F_%T")
-    local oldrelease="$(zfs get -H -o value org.freebsd.iocage:release $dataset)"
-
-    if [ $jail_type == "basejail" ] ; then
-        zfs set org.freebsd.iocage:release="$release" $dataset
+    if [ $_jail_type == "basejail" ] ; then
+        zfs set org.freebsd.iocage:release="$release" $_dataset
         # Re-clone required filesystems
-        __reclone_basejail $name
-        cp -Rp ${mountpoint}/root/etc ${mountpoint}/root/etc.old
-        etcupdate -D ${mountpoint}/root -F \
+        __reclone_basejail $_name
+        cp -Rp ${_mountpoint}/root/etc ${_mountpoint}/root/etc.old
+        etcupdate -D ${_mountpoint}/root -F \
         -s $iocroot/base/$release/root/usr/src
-        __chroot "$name" newaliases
-    if [ $? -eq 0 ] ; then
-        echo ""
-        echo "  Upgrade successful. Please restart jail and inspect. Remove ${mountpoint}/root/etc.old if everything is OK."
-        exit 0
-    else
-        echo ""
-        echo "  Etcupdate failed! Backing out."
-        zfs set org.freebsd.iocage:release="$oldrelease" $dataset
-        rm -rf ${mountpoint}/root/etc
-        mv ${mountpoint}/root/etc.old ${mountpoint}/root/etc
-        exit 1
-      fi
+        __chroot "$_name" newaliases
+
+        if [ $? -eq 0 ] ; then
+            echo ""
+            echo "* Upgrade successful. Please restart jail and inspect. Remove ${_mountpoint}/root/etc.old if everything is OK."
+            exit 0
+        else
+            echo ""
+            echo "* etcupdate failed! Backing out."
+            zfs set org.freebsd.iocage:release="$_oldrelease" $_dataset
+            rm -rf ${_mountpoint}/root/etc
+            mv ${_mountpoint}/root/etc.old ${_mountpoint}/root/etc
+            exit 1
+        fi
     fi
 
-    echo "* creating back-out snapshot.."
-    __snapshot ${fulluuid}@ioc-upgrade_${date}
+    echo "* Creating back-out snapshot."
+    __snapshot ${_fulluuid}@ioc-upgrade_${_date}
 
-    echo "* Upgrading jail.."
+    echo "* Upgrading jail."
 
-    env UNAME_r=${oldrelease} env PAGER="/bin/cat" \
+    env UNAME_r=${_oldrelease} env PAGER="/bin/cat" \
         /usr/sbin/freebsd-update \
-        -b ${mountpoint}/root \
-        -d ${mountpoint}/root/var/db/freebsd-update/ \
+        -b ${_mountpoint}/root \
+        -d ${_mountpoint}/root/var/db/freebsd-update/ \
         -r $release upgrade
 
     if [ $? -eq 0 ] ; then
         while [ $? -eq 0 ] ; do
-            env UNAME_r=${oldrelease} env PAGER="/bin/cat" \
+            env UNAME_r=${_oldrelease} env PAGER="/bin/cat" \
             /usr/sbin/freebsd-update \
-            -b ${mountpoint}/root \
-            -d ${mountpoint}/root/var/db/freebsd-update/ \
+            -b ${_mountpoint}/root \
+            -d ${_mountpoint}/root/var/db/freebsd-update/ \
             -r $release install
     done
 
     # Set jail's zfs property to new release
-    zfs set org.freebsd.iocage:release="$release" $dataset
+    zfs set org.freebsd.iocage:release="$release" $_dataset
     else
-       echo "  Upgrade failed, aborting install."
+       echo "* Upgrade failed, aborting install."
        exit 1
     fi
 
-    echo " "
+    echo ""
     echo "* Once finished don't forget to remove the snapshot!"
 }
diff --git a/lib/ioc-zfs b/lib/ioc-zfs
--- a/lib/ioc-zfs
+++ b/lib/ioc-zfs
@@ -69,6 +69,7 @@ __reclone_basejail () {
 __create_jail () {
     local _installed _releases _zfsconfig _supported_release _configured \
           _zfsconfig
+
     _installed=$(zfs list -r $pool/iocage/releases|grep $release)
     _releases=$(__list_jails -r|grep -v "Downloaded releases:")
     _supported_release=$(echo "$release" | grep "RELEASE")
@@ -86,12 +87,12 @@ __create_jail () {
         echo "  ERROR: No RELEASEs found locally, run iocage fetch first."
         exit 1
     elif [ -z "$_installed" ] ; then
-      echo "  RELEASE $release not found locally."
-      echo "  Please fetch $release or rerun iocage with release=RELEASE"
-      echo ""
-      echo "  These are the releases you have already fetched:"
-      echo "  $_releases"
-      exit 1
+        echo "  RELEASE $release not found locally."
+        echo "  Please fetch $release or rerun iocage with release=RELEASE"
+        echo ""
+        echo "  These are the releases you have already fetched:"
+        echo "  $_releases"
+        exit 1
     fi
 
     if [ "${2}" = "-c" ] ; then
