******* BREAKING CHANGE -- Please read ******* Basejails are now the default jail type unless a switch is present. That means the '-b' switch is gone and calling 'iocage create' will now use them by default. This is a breaking change, older jails that were thick/clone jails will not be able to be upgraded. If you have an old thick jail, just do a 'iocage set type=thickjail UUID|TAG' and you will be fine. Clone jails by their nature are dependent on the old RELEASE datasets and create an odd relationship for users thinking they aren't still using that dataset. So we decided not to officially support them for upgrading. The update and upgrade functions have been rewritten as it erroneously was using the host's /usr/src for the etcupdate routine. Also updated the docs to reflect this. We now do not carry over the RELEASES in the POOL/iocage/download dataset. They aren't actively used and have no reason to stick around after the fetch function is complete. Basejail migration will come later, but for now they are not usable. Only newly created basejails are.

diff --git a/lib/ioc-upgrade b/lib/ioc-upgrade
--- a/lib/ioc-upgrade
+++ b/lib/ioc-upgrade
@@ -43,7 +43,7 @@ __update () {
                     # Update the local git repo to the latest remote
                     git -C $_mountpoint/root pull
                 ;;
-                jail)
+                *)
                     echo "* Creating back-out snapshot."
                     __snapshot ${_fulluuid}@ioc-update_${_date}
 
@@ -55,23 +55,26 @@ __update () {
                         release="$_jail_release"
                     fi
 
-                    _non_interactive="--not-running-from-cron"
-                    if [ $(uname -U) -lt 1002000 ] ; then
-                        _non_interactive=""
-                    fi
-
-                    if [ -e $iocroot/releases/$release/root/etc/freebsd-update.conf ] ; then
-                        env UNAME_r="$release" env PAGER="/bin/cat" \
-                            /usr/sbin/freebsd-update \
-                            $_non_interactive \
-                            -b ${_mountpoint}/root \
-                            -f $iocroot/releases/$release/root/etc/freebsd-update.conf \
-                            -d ${_mountpoint}/root/var/db/freebsd-update/ fetch
-                        env UNAME_r="$release" env PAGER="/bin/cat" \
-                            /usr/sbin/freebsd-update \
-                            -b ${_mountpoint}/root \
-                            -f $iocroot/releases/$release/root/etc/freebsd-update.conf \
-                            -d ${_mountpoint}/root/var/db/freebsd-update/ install
+                    if [ -e ${iocroot}/releases/${release}/root/etc/freebsd-update.conf ] ; then
+                        if [ ! -e ${_mountpoint}/root/etc/resolv.conf ] ; then
+                            export _resolv=1
+                            cat /etc/resolv.conf > \
+                            ${_mountpoint}/root/etc/resolv.conf
+                        fi
+                        mount -t devfs devfs \
+                            ${_mountpoint}/root/dev
+                        chroot ${_mountpoint}/root \
+                            env UNAME_r="${release}" env PAGER="/bin/cat" \
+                            freebsd-update fetch
+                        chroot ${_mountpoint}/root \
+                            env UNAME_r="${release}" env PAGER="/bin/cat" \
+                            freebsd-update install
+                        umount ${_mountpoint}/root/dev
+                        if [ "${_resolv}" = "1" ] ; then
+                            if [ "$?" == "0" ] ; then
+                                rm -f ${_mountpoint}/root/etc/resolv.conf
+                            fi
+                        fi
                     fi
 
                     echo ""
@@ -91,88 +94,108 @@ __update () {
 }
 
 __upgrade () {
-    local _name _dataset _fulluuid _jail_type _jail_release _mountpoint _date \
+    local _name _fulluuid _jail_type _jail_release _mountpoint _date \
           _oldrelease
 
-    _name=$1
-    _dataset="$(__find_jail $_name)" || exit $?
-    _fulluuid="$(__check_name $_name)"
-    _jail_type="$(__get_jail_prop type $_fulluuid)"
-    _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
-    _date=$(date "+%F_%T")
-    _oldrelease="$(zfs get -H -o value org.freebsd.iocage:release $_dataset)"
+    _name="$1"
+    _dataset="$(__find_jail ${_name})" || exit $?
+    _fulluuid="$(__check_name ${_name})"
+    _jail_type="$(__get_jail_prop type ${_fulluuid})"
+    _mountpoint="$(__get_jail_prop mountpoint ${_fulluuid})"
+    _oldrelease="$(zfs get -H -o value org.freebsd.iocage:release ${_dataset})"
 
-    if [ -z $_name ] ; then
+    if [ -z ${_name} ] ; then
         __die "missing UUID!"
     fi
 
-    if [ -z $_dataset ] ; then
-        __die "$_name not found!"
+    if [ -z ${_dataset} ] ; then
+        __die "${_name} not found!"
     fi
 
-    if [ ! -d $iocroot/download/$release ] ; then
-        __error "$release not found!"
+    if [ ! -d ${iocroot}/releases/${release} ] ; then
+        __error "${release} not found!"
         echo "  Please run iocage fetch first."
         exit 1
     fi
 
     # If jail is a basejail then set the new release and reclone the datasets
-    # also backup jail's /etc just incase etcupdate doesn't go as planned
-    if [ $_jail_type == "basejail" ] ; then
-        zfs set org.freebsd.iocage:release="$release" $_dataset
-        # Re-clone required filesystems
-        __reclone_basejail $_name
-        cp -Rp ${_mountpoint}/root/etc ${_mountpoint}/root/etc.old
+    # also backup jail's /etc just in-case etcupdate doesn't go as planned
+    if [ ${_jail_type} == "basejail" ] ; then
+        __reclone_basejail ${_fulluuid} > /dev/null 2>&1
+        zfs set org.freebsd.iocage:release="${release}" ${_dataset}
+        cp -Rp ${_mountpoint}/root/etc \
+               ${_mountpoint}/etc.old
+        zfs snapshot ${_dataset}/var@ioc-upgrade_$(date +%F)
         etcupdate -D ${_mountpoint}/root -F \
-        -s $iocroot/base/$release/root/usr/src
-        __chroot "$_name" newaliases
+            -s ${iocroot}/releases/${release}/root/usr/src
+        if [ -e ${_mountpoint}/root/var/spool/mqueue ] ; then
+            __chroot ${_fulluuid} newaliases
+        else
+            mkdir -p ${_mountpoint}/root/var/spool/mqueue
+            __chroot ${_fulluuid} newaliases
+        fi
 
         # Check for zero exit code(success) otherwise bail and revert everything
         if [ $? -eq 0 ] ; then
+            __reclone_basejail ${_fulluuid} > /dev/null 2>&1
             echo ""
-            echo "* Upgrade successful. Please restart jail and inspect. Remove ${_mountpoint}/root/etc.old if everything is OK."
+            echo "* Upgrade successful. Please restart jail and inspect."
+            echo "* Remove:"
+            echo "    etc backup: ${_mountpoint}/etc.old"
+            echo "    /var snapshot: ${_dataset}/var@ioc-upgrade_$(date +%F)"
+            echo "* if everything is OK."
             exit 0
         else
             echo ""
             echo "* etcupdate failed! Backing out."
-            zfs set org.freebsd.iocage:release="$_oldrelease" $_dataset
-            rm -rf ${_mountpoint}/root/etc
-            mv ${_mountpoint}/root/etc.old ${_mountpoint}/root/etc
+            zfs set org.freebsd.iocage:release="${_oldrelease}" ${_dataset}
+            zfs rollback -rRf ${_dataset}/var@ioc-upgrade_$(date +%F)
+            zfs destroy ${_dataset}/var@ioc-upgrade_$(date +%F)
+            umount ${_mountpoint}/root/etc
+            rm -rf ${_mountpoint}/etc
+            mv ${_mountpoint}/etc.old \
+               ${_mountpoint}/etc
             exit 1
         fi
-    fi
+    elif [ ${_jail_type} == "thickjail" ] ; then
 
-    echo "* Creating back-out snapshot."
-    __snapshot ${_fulluuid}@ioc-upgrade_${_date}
+        echo "* Creating back-out snapshot."
+        __snapshot ${_fulluuid}@ioc-upgrade_${_date}
 
-    echo "* Upgrading jail."
+        echo "* Upgrading jail."
 
-    # Override the release that freebsd-update uses and
-    # set the pager to cat so that it isn't interactive
-    env UNAME_r=${_oldrelease} env PAGER="/bin/cat" \
-        /usr/sbin/freebsd-update \
-        -b ${_mountpoint}/root \
-        -d ${_mountpoint}/root/var/db/freebsd-update/ \
-        -r $release upgrade
+        if [ -e ${iocroot}/releases/${release}/root/etc/freebsd-update.conf ] ; then
+            if [ ! -e ${_mountpoint}/root/etc/resolv.conf ] ; then
+                export _resolv=1
+                cat /etc/resolv.conf > \
+                    ${_mountpoint}/root/etc/resolv.conf
+            fi
+            mount -t devfs devfs \
+                ${_mountpoint}/root/dev
+            chroot ${_mountpoint}/root \
+                env UNAME_r="${_oldrelease}" env PAGER="/bin/cat" \
+                freebsd-update -r ${release} upgrade
+            if [ $? -eq 0 ] ; then
+                while [ $? -eq 0 ] ; do
+                    chroot ${_mountpoint}/root \
+                        env UNAME_r="${_oldrelease}" env PAGER="/bin/cat" \
+                        freebsd-update -r ${release} install
+                done
+                if [ "${_resolv}" = "1" ] ; then
+                    rm -f ${_mountpoint}/root/etc/resolv.conf
+                fi
+            fi
+        umount ${_mountpoint}/root/dev
+        # Set jail's zfs property to new release
+        zfs set org.freebsd.iocage:release="$release" $_dataset
+        else
+           echo "* Upgrade failed, aborting install."
+           exit 1
+        fi
 
-    # Same as above except it waits to see a non-zero exit code signalling that
-    # there isn't anything else left to do
-    if [ $? -eq 0 ] ; then
-        while [ $? -eq 0 ] ; do
-            env UNAME_r=${_oldrelease} env PAGER="/bin/cat" \
-            /usr/sbin/freebsd-update \
-            -b ${_mountpoint}/root \
-            -d ${_mountpoint}/root/var/db/freebsd-update/ \
-            -r $release install
-    done
-
-    # Set jail's zfs property to new release
-    zfs set org.freebsd.iocage:release="$release" $_dataset
+        echo ""
+        echo "* Once finished don't forget to remove the snapshot!"
     else
-       echo "* Upgrade failed, aborting install."
-       exit 1
+        __die "upgrade is not supported for this type of jail"
     fi
-
-    echo ""
-    echo "* Once finished don't forget to remove the snapshot!"
 }
