Fixed destroy basejails & ALL, also introduced -f for non interactive destroy

diff --git a/lib/ioc-zfs b/lib/ioc-zfs
--- a/lib/ioc-zfs
+++ b/lib/ioc-zfs
@@ -1,36 +1,24 @@
 #!/bin/sh
 
 # check if .defaults dataset exists, if not create it
-zfs get -H creation ${pool}${iocroot}/.defaults > /dev/null 2>&1
-if [ $? -ne 0 ] ; then
-    echo "  INFO: Creating ${pool}${iocroot}/.defaults."
-    zfs create ${pool}${iocroot}/.defaults
-fi
+__check_defaults () {
+    zfs get -H creation ${pool}${iocroot}/.defaults > /dev/null 2>&1
+    if [ $? -ne 0 ] ; then
+        echo "  INFO: Creating ${pool}${iocroot}/.defaults."
+        zfs create ${pool}${iocroot}/.defaults
+    fi
+}
 
 __create_basejail () {
-    local release="$1"
-    local fs_list="bin
-                   boot
-                   lib
-                   libexec
-                   rescue
-                   sbin
-                   usr
-                   usr/bin
-                   usr/include
-                   usr/lib
-                   usr/libexec
-                   usr/sbin
-                   usr/share
-                   usr/src
-                   usr/libdata
-                   usr/lib32"
+    local _release
+
+    _release="$1"
 
     echo ""
     echo "Creating basejail ZFS datasets... please wait."
 
-    for fs in $(echo $fs_list) ; do
-        zfs create -o compression=lz4 -p $pool/iocage/base/${release}/root/$fs
+    for fs in $(echo $bfs_list) ; do
+        zfs create -o compression=lz4 -p $pool/iocage/base/${_release}/root/$fs
     done
 }
 
@@ -189,87 +177,48 @@ __clone_jail () {
 
 # Destroy jails --------------------------------------------------------------
 __destroy_jail () {
-    local name=$1
+    local _name _answer _uuid_list _force
 
-    if [ -z $name ] ; then
+    if [ -z "$1" ] ; then
         echo "  ERROR: missing UUID!"
         exit 1
     fi
 
-    local release_list="$(zfs list -o name -Hr $pool/iocage/releases \
-                        | grep RELEASE$ | cut -d \/ -f 4)"
+    if [ "$1" == '-f' ] ; then
+        _force="1"
+        _name="$2"
+    else
+        _force="0"
+        _name="$1"
+    fi
 
-    local fs_list="bin
-                   boot
-                   lib
-                   libexec
-                   rescue
-                   sbin
-                   usr
-                   usr/bin
-                   usr/include
-                   usr/lib
-                   usr/libexec
-                   usr/sbin
-                   usr/share
-                   usr/src
-                   usr/libdata
-                   usr/lib32"
-
-    if [ $name == "ALL" ] ; then
+    if [ $_name == "ALL" ] ; then
         echo " "
         echo "  WARNING: this will destroy ALL jails"
         echo " "
         echo "  Please make sure all jails are stopped before continuing."
         echo " "
         echo -n "  Are you sure ? Y[n]: "
-        read answer
+        read _answer
 
-    if [ "$answer" == "Y" ]; then
-        echo "  Destroying all jails"
-        zfs destroy -rf ${pool}${iocroot}/jails
-        zfs destroy -rf ${pool}${iocroot}/tags
-        for release in $(echo $release_list) ; do
-            for fslist in $fs_list ; do
+        if [ "$_answer" == "Y" ]; then
+            echo "  Destroying all jails"
+            _force="1"
 
-                local uuid_list="$(zfs list -Hrt snapshot -o name | grep \
-                    ^${pool}${iocroot}/base/${release}/root/${fslist}@)"
-                for jailsnaps in $(echo $uuid_list) ; do
-                     zfs destroy -rf ${jailsnaps}
-                done
+            __destroy_all
+            rm -f ${iocroot}/tags/*
 
-                local uuid_list="$(zfs list -Hrt snapshot -o name | grep \
-                    ^${pool}${iocroot}/base/${release}/root@)"
-                for rootsnaps in $(echo $uuid_list) ; do
-                    zfs destroy -rf ${rootsnaps}
-                done
-
-                local uuid_list="$(zfs list -Hrt snapshot -o name | grep \
-                    ^${pool}${iocroot}/base/${release}@)"
-                for releasesnaps in $(echo $uuid_list) ; do
-                    zfs destroy -rf ${releasesnaps}
-                done
-
-                local uuid_list="$(zfs list -Hrt snapshot -o name | grep \
-                    ^${pool}${iocroot}/base@)"
-                for basesnaps in $(echo $uuid_list) ; do
-                    zfs destroy -rf ${basesnaps}
-                done
-            done
-        done
-             zfs create -o compression=lz4 ${pool}${iocroot}/jails
-             zfs create -o compression=lz4 ${pool}${iocroot}/tags
-             exit 0
+            exit 0
+        else
+            echo "  Command not confirmed.  No action taken."
+            exit 1
         fi
-    else
-        echo "  Command not confirmed.  No action taken."
-        exit 1
     fi
 
-    local dataset="$(__find_jail $name)"
+    local dataset="$(__find_jail $_name)"
 
     if [ -z $dataset ] ; then
-        echo "  ERROR: $name not found."
+        echo "  ERROR: $_name not found."
         exit 1
     fi
 
@@ -279,43 +228,59 @@ __destroy_jail () {
     fi
 
     local origin="$(zfs get -H -o value origin $dataset)"
-    local fulluuid="$(__check_name $name)"
+    local fulluuid="$(__check_name $_name)"
     local jail_path="$(__get_jail_prop mountpoint $fulluuid)"
     local state="$(jls | grep ${jail_path} | wc -l)"
     local jail_type="$(__get_jail_prop type $fulluuid)"
     local jail_release="$(__get_jail_prop release $fulluuid)"
 
-    echo " "
-    echo "  WARNING: this will destroy jail $fulluuid"
-    echo "  Dataset: $dataset"
-    echo " "
-    echo -n "  Are you sure ? Y[n]: "
-    read answer
+    if [ "$_force" -ne "1" ] ; then
+        echo " "
+        echo "  WARNING: this will destroy jail $fulluuid"
+        echo "  Dataset: $dataset"
+        echo " "
+        echo -n "  Are you sure ? Y[n]: "
+        read _answer
 
-    if [ "$answer" == "Y" ]; then
-        if [ "$state" -lt "1" ] ; then
-            echo "  Destroying: $fulluuid"
+        __destroy_func
 
-            __unlink_tag $dataset
-
-            zfs destroy -fr $dataset
-
-            if [ "$origin" != "-" ] ; then
-                echo "  Destroying clone origin: $origin"
-                zfs destroy -r $origin
-            fi
-
-            if [ $jail_type == "basejail" ] ; then
-                zfs destroy -fr $pool/iocage/base/$jail_release@$fulluuid
-            fi
-
-        elif [ "$state" -eq "1" ] ; then
-            echo "  ERROR: Jail is up and running. Exiting."
-            exit 1
-        fi
-   else
-       echo "  Command not confirmed.  No action taken."
-   fi
-
+    elif [ "$_force" -eq "1" ] ; then
+        __destroy_func
+    else
+        echo "  Command not confirmed.  No action taken."
+        echo $_force
+        exit 1
+    fi
 }
 
+__destroy_func () {
+    if [ "$state" -lt "1" ] ; then
+        echo "  Destroying: $fulluuid"
+        __unlink_tag $dataset
+
+        zfs destroy -fr $dataset
+
+        if [ "$origin" != "-" ] ; then
+            echo "  Destroying clone origin: $origin"
+            zfs destroy -r $origin
+        fi
+
+        if [ $jail_type == "basejail" ] ; then
+            zfs destroy -fr $pool/iocage/base@$fulluuid
+        fi
+
+    elif [ "$state" -eq "1" ] ; then
+        echo "  ERROR: Jail is up and running. Exiting."
+        exit 1
+    fi
+}
+
+__destroy_all () {
+    local _jails _fulluuid
+    _jails="$(__find_jail ALL)"
+
+    for jail in $_jails ; do
+        _fulluuid="$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)"
+        __destroy_jail "-f" "$_fulluuid"
+    done
+}
