Change to how we assign AUTOIP4 addresses. Now we will go through the range in ascending order, checking if an IP4 address is available in the pool, before assigning it.
This means when a jail is destroyed, the automatic IP4 address can
be re-assigned to a new jail. Also, if somebody manually creates
a jail with an IP in that range, it won't be assigned on top of it.

diff --git a/lib/ioc-network b/lib/ioc-network
--- a/lib/ioc-network
+++ b/lib/ioc-network
@@ -144,29 +144,62 @@ __networking () {
 }
 
 __get_autoip4 () {
-     local _autobase _autostart _autoend _autoip
+     local _autobase _autostart _autoend _autoip _freeip
      unset _auto_ip4
      _autobase=$(netstat -f inet -nrW | grep '^default' |\
 		awk '{ print $2 }' | cut -d '.' -f 1-3)
      _autostart=$(__get_jail_prop ip4_autostart default)
      _autoend=$(__get_jail_prop ip4_autoend default)
+     local jails=$(__find_jail ALL)
 
-     # KPM - 2015-07-24
-     # !!Brandon!! - This needs to be re-worked so instead
-     # of just blindly taking the next IP address, we should
-     # search through the jails and get the next available
-     # ip address. So that we can re-use IPs when jails
-     # using them are deleted
-
-     _autoip="$(expr $_autostart + 1)"
-     if [ ${_autoip} -gt ${_autoend} ] ; then
-       echo "  ERROR: $_autoip is higher then $_autoend!"
-       echo "  Please increase $_autoend."
-       exit 1
+     # Do some basic sanity checking
+     if [ -z "$_autostart" ] ; then
+	echo "ERROR: AUTOIP4 is specified, but ip4_autostart is not set!"
+        exit 1
+     fi
+     if [ -z "$_autoend" ] ; then
+	echo "ERROR: AUTOIP4 is specified, but ip4_autoend is not set!"
+        exit 1
      fi
 
+     # Now loop through all the jails, and find a free IP we can use
+     # that fits within the autostart/autoend ranges
+     _autoip=$_autostart
+     while :
+     do
+       _freeip="YES"
+       _nextaddr="${_autobase}.${_autoip}"
+       # Is this address in use?
+       for jail in $jails ; do
+	  local juuid=$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)
+          local jip4="$(__get_jail_prop ip4_addr ${juuid})"
+          jip4=$(echo $jip4 | cut -d '|' -f 2 | cut -d '/' -f 1)
+	  if [ "$jip4" = "$_nextaddr" ] ; then
+             _freeip="NO"
+             break
+          fi
+       done
+
+       # On to the next entry to try
+       if [ "$_freeip" = "NO" ] ; then
+          _autoip=$(expr $_autoip + 1)
+          continue
+       fi
+
+       # Sanity check
+       if [ $_autoip -gt $_autoend ] ; then
+          echo "ERROR: IP4 Automatic Address exhaustion"
+          exit 1
+       fi
+       if [ $_autoip -gt 254 ] ; then
+          echo "ERROR: IP4 Address outside of bounds"
+          exit 1
+       fi
+       break
+     done
+
      # Set our new ip address
-     auto_ip4="${_autobase}.${_autoip}"
+     auto_ip4="$_nextaddr"
 }
 
 __stop_legacy_networking () {
